/// Écoles d'origine possibles pour le CEPE (feuille 'ecoleDoridineCEPE').
/// Généré depuis stageCisco.xlsx — 384 entrées.
const List<Map<String, dynamic>> ecoleOrigineCepe = [
  {
    'codeEcoleOrigine': 703,
    'codeEtab': 326061001,
    'ecoleOrigine': 'COLLEGE PRIVE FJKM AMBALAMANENJANA I',
    'centreExamen': 'F02/01',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 704,
    'codeEtab': 326061002,
    'ecoleOrigine': 'COLLEGE VICTOIRE RASOAMANARIVO MORALINA',
    'centreExamen': 'F02/01',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 705,
    'codeEtab': 326061011,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE ANKISIRA',
    'centreExamen': 'F02/01',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 706,
    'codeEtab': 326061010,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE AMBABO',
    'centreExamen': 'F02/01',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 707,
    'codeEtab': 326061003,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE AMBALAHAZO',
    'centreExamen': 'F02/01',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 708,
    'codeEtab': 326061004,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE AMBALAMANENJANA II',
    'centreExamen': 'F02/01',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 709,
    'codeEtab': 326061006,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE ANTSAHAMBORONDOLO',
    'centreExamen': 'F02/01',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 710,
    'codeEtab': 326061007,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE MAROFOTOTRA',
    'centreExamen': 'F02/01',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 711,
    'codeEtab': 326060003,
    'ecoleOrigine': 'EPP AMBALAHAZO',
    'centreExamen': 'F02/01',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 712,
    'codeEtab': 326030020,
    'ecoleOrigine': 'EPP AMBALAMIJEA',
    'centreExamen': 'F02/01',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 713,
    'codeEtab': 326060004,
    'ecoleOrigine': 'EPP AMBALAMIRARY',
    'centreExamen': 'F02/01',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 714,
    'codeEtab': 326060005,
    'ecoleOrigine': 'EPP AMBALASOA',
    'centreExamen': 'F02/01',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 715,
    'codeEtab': 326060006,
    'ecoleOrigine': 'EPP AMBATOTERAKA',
    'centreExamen': 'F02/01',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 716,
    'codeEtab': 326060024,
    'ecoleOrigine': 'EPP AMBATOVORY',
    'centreExamen': 'F02/01',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 717,
    'codeEtab': 326030009,
    'ecoleOrigine': 'EPP AMBOHIBOLAMENA',
    'centreExamen': 'F02/01',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 718,
    'codeEtab': 326060007,
    'ecoleOrigine': 'EPP AMBOHIBORY MORALINA',
    'centreExamen': 'F02/01',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 719,
    'codeEtab': 326060008,
    'ecoleOrigine': 'EPP ANDRAVINDAHY',
    'centreExamen': 'F02/01',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 720,
    'codeEtab': 326060009,
    'ecoleOrigine': 'EPP ANTSAHAMBORONDOLO',
    'centreExamen': 'F02/01',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 721,
    'codeEtab': 326040004,
    'ecoleOrigine': 'EPP FANAMEANA SOALOZOKA',
    'centreExamen': 'F02/01',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 722,
    'codeEtab': 326040004,
    'ecoleOrigine': 'EPP FANAMEANA SOALOZOKA',
    'centreExamen': 'F02/01',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 723,
    'codeEtab': 326060011,
    'ecoleOrigine': 'EPP MANAMISOA',
    'centreExamen': 'F02/01',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 724,
    'codeEtab': 326060012,
    'ecoleOrigine': 'EPP SABOTSY MAHADITRA',
    'centreExamen': 'F02/01',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 725,
    'codeEtab': 326060014,
    'ecoleOrigine': 'EPP TAMBOHOBE I',
    'centreExamen': 'F02/01',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 726,
    'codeEtab': 326060015,
    'ecoleOrigine': 'EPP TAMBOHOSOA',
    'centreExamen': 'F02/01',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 727,
    'codeEtab': 326060016,
    'ecoleOrigine': 'EPP TSIMAITOHASOA IALATSARA',
    'centreExamen': 'F02/01',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 728,
    'codeEtab': 326060017,
    'ecoleOrigine': 'EPP TSITARY',
    'centreExamen': 'F02/01',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 729,
    'codeEtab': 326011008,
    'ecoleOrigine': 'COLLEGE PRIVE FJKM TSARAFARA',
    'centreExamen': 'F02/02',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 730,
    'codeEtab': 326151001,
    'ecoleOrigine': 'ECOLE PRIVE CATHOLIQUE JEAN BOSCO TAMBOHOMANDREVO',
    'centreExamen': 'F02/02',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 731,
    'codeEtab': 326011009,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE AMBALADIMY',
    'centreExamen': 'F02/02',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 732,
    'codeEtab': 326011001,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE AMBALAMARINA EST',
    'centreExamen': 'F02/02',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 733,
    'codeEtab': 326011002,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE SAINT JEAN BOSCO',
    'centreExamen': 'F02/02',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 734,
    'codeEtab': 326011003,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE ST IGNACE IVATO',
    'centreExamen': 'F02/02',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 735,
    'codeEtab': 326010004,
    'ecoleOrigine': 'EPP ALAKAMISY ITENINA',
    'centreExamen': 'F02/02',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 736,
    'codeEtab': 326010005,
    'ecoleOrigine': 'EPP AMBALAFAHIBATO',
    'centreExamen': 'F02/02',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 737,
    'codeEtab': 326010006,
    'ecoleOrigine': 'EPP AMBALATAVY',
    'centreExamen': 'F02/02',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 738,
    'codeEtab': 326060008,
    'ecoleOrigine': 'EPP ANDRAVINDAHY',
    'centreExamen': 'F02/02',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 739,
    'codeEtab': 326010007,
    'ecoleOrigine': 'EPP ANJAMANA',
    'centreExamen': 'F02/02',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 740,
    'codeEtab': 326010022,
    'ecoleOrigine': 'EPP FANIRIANTSOA',
    'centreExamen': 'F02/02',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 741,
    'codeEtab': 326040005,
    'ecoleOrigine': 'EPP IHAFADRAY',
    'centreExamen': 'F02/02',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 742,
    'codeEtab': 326010008,
    'ecoleOrigine': 'EPP MAROSALAZANA',
    'centreExamen': 'F02/02',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 743,
    'codeEtab': 326010009,
    'ecoleOrigine': 'EPP MIANDRIVAO',
    'centreExamen': 'F02/02',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 744,
    'codeEtab': 326010010,
    'ecoleOrigine': 'EPP RIAMBARY',
    'centreExamen': 'F02/02',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 745,
    'codeEtab': 326010011,
    'ecoleOrigine': 'EPP SAHAVINDRANINA',
    'centreExamen': 'F02/02',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 746,
    'codeEtab': 326010012,
    'ecoleOrigine': 'EPP SANGASANGA NORD',
    'centreExamen': 'F02/02',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 747,
    'codeEtab': 326010013,
    'ecoleOrigine': 'EPP SOATSIHADINO',
    'centreExamen': 'F02/02',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 748,
    'codeEtab': 326010014,
    'ecoleOrigine': 'EPP TANDROKAZO',
    'centreExamen': 'F02/02',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 749,
    'codeEtab': 326010021,
    'ecoleOrigine': 'EPP TARATRA',
    'centreExamen': 'F02/02',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 750,
    'codeEtab': 326010015,
    'ecoleOrigine': 'EPP TSILAZO LOVASOA',
    'centreExamen': 'F02/02',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 751,
    'codeEtab': 326010016,
    'ecoleOrigine': 'EPP VIDIAMBOLA',
    'centreExamen': 'F02/02',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 752,
    'codeEtab': 326999901,
    'ecoleOrigine': 'CANDIDAT LIBRE',
    'centreExamen': 'F02/07',
    'secteur': 'LIBRE',
  },
  {
    'codeEcoleOrigine': 753,
    'codeEtab': 326071010,
    'ecoleOrigine': 'ECOLE NON CONFESSIONNELLE AKANY MIZARASOA',
    'centreExamen': 'F02/07',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 754,
    'codeEtab': 326071012,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE AMBALAVAO LALANGINA',
    'centreExamen': 'F02/07',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 755,
    'codeEtab': 326071001,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE AMBOASARIMAY',
    'centreExamen': 'F02/07',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 756,
    'codeEtab': 326021019,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE ANDRANOMBAO',
    'centreExamen': 'F02/07',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 757,
    'codeEtab': 326071003,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE DE TAMBOHOBE',
    'centreExamen': 'F02/07',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 758,
    'codeEtab': 326071004,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE DE TSANGAMAHALAZA',
    'centreExamen': 'F02/07',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 759,
    'codeEtab': 326071011,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE DE VOHIMARINA',
    'centreExamen': 'F02/07',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 760,
    'codeEtab': 326021006,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE TANITSIHOMEHY A',
    'centreExamen': 'F02/07',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 761,
    'codeEtab': 326071015,
    'ecoleOrigine': 'ECOLE PRIVEE NON CONFESSIONNELLE LOVASOA',
    'centreExamen': 'F02/07',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 762,
    'codeEtab': 326070002,
    'ecoleOrigine': 'EPP AMBALAMITSINJONY',
    'centreExamen': 'F02/07',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 763,
    'codeEtab': 326070003,
    'ecoleOrigine': 'EPP AMBALANDAPA',
    'centreExamen': 'F02/07',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 764,
    'codeEtab': 326070004,
    'ecoleOrigine': 'EPP AMBALANDRAMENA',
    'centreExamen': 'F02/07',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 765,
    'codeEtab': 326070005,
    'ecoleOrigine': 'EPP AMBALAVAO MAHAZOARIVO',
    'centreExamen': 'F02/07',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 766,
    'codeEtab': 326070006,
    'ecoleOrigine': 'EPP AMBATOLAHY',
    'centreExamen': 'F02/07',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 767,
    'codeEtab': 326070007,
    'ecoleOrigine': 'EPP AMBATOMIFANONGOA',
    'centreExamen': 'F02/07',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 768,
    'codeEtab': 326070008,
    'ecoleOrigine': 'EPP AMPAMERENANA',
    'centreExamen': 'F02/07',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 769,
    'codeEtab': 326070009,
    'ecoleOrigine': 'EPP ANDRAKAJAHA MAHASOABE',
    'centreExamen': 'F02/07',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 770,
    'codeEtab': 326070010,
    'ecoleOrigine': 'EPP ANDRANONDAMBO',
    'centreExamen': 'F02/07',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 771,
    'codeEtab': 326070011,
    'ecoleOrigine': 'EPP IAMBARA SOANATAO',
    'centreExamen': 'F02/07',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 772,
    'codeEtab': 326070009,
    'ecoleOrigine': 'EPP MAHASOABE',
    'centreExamen': 'F02/07',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 773,
    'codeEtab': 326070012,
    'ecoleOrigine': 'EPP MAHASOAKELY',
    'centreExamen': 'F02/07',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 774,
    'codeEtab': 326070013,
    'ecoleOrigine': 'EPP MANAGARIVOTRA',
    'centreExamen': 'F02/07',
    'secteur': 'Public',
  },
  {
    'codeEcoleOrigine': 775,
    'codeEtab': 326070014,
    'ecoleOrigine': 'EPP SAHAMALAZA',
    'centreExamen': 'F02/07',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 776,
    'codeEtab': 326070015,
    'ecoleOrigine': 'EPP SOAMANANDRARINY',
    'centreExamen': 'F02/07',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 777,
    'codeEtab': 326070016,
    'ecoleOrigine': 'EPP SOANIERANA MAROVITSIKA',
    'centreExamen': 'F02/07',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 778,
    'codeEtab': 326070017,
    'ecoleOrigine': 'EPP TAMBOHOBE',
    'centreExamen': 'F02/07',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 779,
    'codeEtab': 326070018,
    'ecoleOrigine': 'EPP TANAMBAO MANAMISOA',
    'centreExamen': 'F02/07',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 780,
    'codeEtab': 326070019,
    'ecoleOrigine': 'EPP TSANGAMAHALAZA',
    'centreExamen': 'F02/07',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 781,
    'codeEtab': 326071005,
    'ecoleOrigine': 'LYCEE CATHOLIQUE ST LOUIS DE GONZAGUE',
    'centreExamen': 'F02/07',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 782,
    'codeEtab': 326100001,
    'ecoleOrigine': 'EPP AMBALAFANDRAMBATO',
    'centreExamen': 'F02/08',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 783,
    'codeEtab': 326100002,
    'ecoleOrigine': 'EPP AMBALATSIMIFARY',
    'centreExamen': 'F02/08',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 784,
    'codeEtab': 326100008,
    'ecoleOrigine': 'EPP IALADALANGY',
    'centreExamen': 'F02/08',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 785,
    'codeEtab': 326100013,
    'ecoleOrigine': 'EPP MAROVORY',
    'centreExamen': 'F02/08',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 786,
    'codeEtab': 326999901,
    'ecoleOrigine': 'CANDIDAT LIBRE',
    'centreExamen': 'F02/08',
    'secteur': 'LIBRE',
  },
  {
    'codeEcoleOrigine': 787,
    'codeEtab': 326101007,
    'ecoleOrigine': 'COLLEGE PRIVEE CATHOLIQUE SAINT STANISLAS KOSTKA',
    'centreExamen': 'F02/08',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 788,
    'codeEtab': 326101002,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE IJERY',
    'centreExamen': 'F02/08',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 789,
    'codeEtab': 326101003,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE SAINT PIERRE MANAOKOA',
    'centreExamen': 'F02/08',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 790,
    'codeEtab': 326101004,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE SOAVADIA MAROVOVOTANY',
    'centreExamen': 'F02/08',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 791,
    'codeEtab': 326101005,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE ST JOSEPH AMPANO',
    'centreExamen': 'F02/08',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 792,
    'codeEtab': 326101006,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE ST JOSEPH MANDRANOMAVO',
    'centreExamen': 'F02/08',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 793,
    'codeEtab': 326101012,
    'ecoleOrigine': 'ECOLE PRIVEE FLEURIA SCHOOL',
    'centreExamen': 'F02/08',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 794,
    'codeEtab': 326101011,
    'ecoleOrigine': 'ECOLE PRIVEE SAINT JOSEPH TANJOMBITA',
    'centreExamen': 'F02/08',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 795,
    'codeEtab': 326100003,
    'ecoleOrigine': 'EPP  AMBATOMIHALANA',
    'centreExamen': 'F02/08',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 796,
    'codeEtab': 326100004,
    'ecoleOrigine': 'EPP  AMPANO TANAMAY',
    'centreExamen': 'F02/08',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 797,
    'codeEtab': 326100004,
    'ecoleOrigine': 'EPP AMPANO TANAMAY',
    'centreExamen': 'F02/08',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 798,
    'codeEtab': 326100005,
    'ecoleOrigine': 'EPP ANJAMANA',
    'centreExamen': 'F02/08',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 799,
    'codeEtab': 326100006,
    'ecoleOrigine': 'EPP ANKAFOTRA',
    'centreExamen': 'F02/08',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 800,
    'codeEtab': 326100007,
    'ecoleOrigine': 'EPP ANTAKO TANANDAVA',
    'centreExamen': 'F02/08',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 801,
    'codeEtab': 326100009,
    'ecoleOrigine': 'EPP LANGELA',
    'centreExamen': 'F02/08',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 802,
    'codeEtab': 326100010,
    'ecoleOrigine': 'EPP MAHATSANDA',
    'centreExamen': 'F02/08',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 803,
    'codeEtab': 326100011,
    'ecoleOrigine': 'EPP MARODINTA',
    'centreExamen': 'F02/08',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 804,
    'codeEtab': 326100012,
    'ecoleOrigine': 'EPP MAROLOLO EST',
    'centreExamen': 'F02/08',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 805,
    'codeEtab': 326100013,
    'ecoleOrigine': 'EPP MAROVORY',
    'centreExamen': 'F02/08',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 806,
    'codeEtab': 326100014,
    'ecoleOrigine': 'EPP TALATA AMPANO',
    'centreExamen': 'F02/08',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 807,
    'codeEtab': 326110010,
    'ecoleOrigine': 'EPP NANDRAINA',
    'centreExamen': 'F02/09',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 808,
    'codeEtab': 326110026,
    'ecoleOrigine': 'ECOLE COMMUNAUTAIRE AMBOHIMALAZA',
    'centreExamen': 'F02/09',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 809,
    'codeEtab': 326110026,
    'ecoleOrigine': 'ECOLE COMMUNAUTAIRE AMBOHIMALAZA',
    'centreExamen': 'F02/09',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 810,
    'codeEtab': 326110032,
    'ecoleOrigine': 'ECOLE COMMUNAUTAIRE ANKAE',
    'centreExamen': 'F02/09',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 811,
    'codeEtab': 326110036,
    'ecoleOrigine': 'ECOLE COMMUNAUTAIRE FANILO ANOSIVORY',
    'centreExamen': 'F02/09',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 812,
    'codeEtab': 326110034,
    'ecoleOrigine': 'ECOLE COMMUNAUTAIRE LOVASOA',
    'centreExamen': 'F02/09',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 813,
    'codeEtab': 326110023,
    'ecoleOrigine': 'ECOLE COMMUNAUTAIRE MANANTENASOA I',
    'centreExamen': 'F02/09',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 814,
    'codeEtab': 326110031,
    'ecoleOrigine': 'ECOLE COMMUNAUTAIRE MANANTENASOA II',
    'centreExamen': 'F02/09',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 815,
    'codeEtab': 326110016,
    'ecoleOrigine': 'ECOLE COMMUNAUTAIRE MANAOTSARA',
    'centreExamen': 'F02/09',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 816,
    'codeEtab': 326110018,
    'ecoleOrigine': 'ECOLE COMMUNAUTAIRE MANIRISOA',
    'centreExamen': 'F02/09',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 817,
    'codeEtab': 326110018,
    'ecoleOrigine': 'ECOLE COMMUNAUTAIRE MANIRISOA',
    'centreExamen': 'F02/09',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 818,
    'codeEtab': 326110027,
    'ecoleOrigine': 'ECOLE COMMUNAUTAIRE NAMARINA',
    'centreExamen': 'F02/09',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 819,
    'codeEtab': 326110025,
    'ecoleOrigine': 'ECOLE COMMUNAUTAIRE SOANIARENANA I',
    'centreExamen': 'F02/09',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 820,
    'codeEtab': 326110021,
    'ecoleOrigine': 'ECOLE COMMUNAUTAIRE SOANIERENANA',
    'centreExamen': 'F02/09',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 821,
    'codeEtab': 326110025,
    'ecoleOrigine': 'ECOLE COMMUNAUTAIRE SOANIERENANA I',
    'centreExamen': 'F02/09',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 822,
    'codeEtab': 326110028,
    'ecoleOrigine': 'ECOLE COMMUNAUTAIRE SOANIERENANA II',
    'centreExamen': 'F02/09',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 823,
    'codeEtab': 326141007,
    'ecoleOrigine': 'ECOLE PRIVEE  RAINISOALAMBO VATOFOTSY',
    'centreExamen': 'F02/09',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 824,
    'codeEtab': 326111008,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE AMBALAVAO ANTANIMENA',
    'centreExamen': 'F02/09',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 825,
    'codeEtab': 326111002,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE ANDRARAMBINY',
    'centreExamen': 'F02/09',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 826,
    'codeEtab': 326111003,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE BEBITSIKA',
    'centreExamen': 'F02/09',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 827,
    'codeEtab': 326111004,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE IHOROVA',
    'centreExamen': 'F02/09',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 828,
    'codeEtab': 326141008,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE ITANJO',
    'centreExamen': 'F02/09',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 829,
    'codeEtab': 326111005,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE SAHAMA',
    'centreExamen': 'F02/09',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 830,
    'codeEtab': 326141004,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE SAMBOHOVA',
    'centreExamen': 'F02/09',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 831,
    'codeEtab': 326111006,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE TANAMBAO',
    'centreExamen': 'F02/09',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 832,
    'codeEtab': 326141008,
    'ecoleOrigine': 'EP FJKM AMBALAMAHAZOANONY',
    'centreExamen': 'F02/09',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 833,
    'codeEtab': 326110011,
    'ecoleOrigine': 'EPP  SAHARAIVO',
    'centreExamen': 'F02/09',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 834,
    'codeEtab': 326140002,
    'ecoleOrigine': 'EPP AMBALAHAMBANA',
    'centreExamen': 'F02/09',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 835,
    'codeEtab': 326110003,
    'ecoleOrigine': 'EPP AMBALAMANENJANA',
    'centreExamen': 'F02/09',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 836,
    'codeEtab': 326110004,
    'ecoleOrigine': 'EPP AMBALAVAO SAHAFA',
    'centreExamen': 'F02/09',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 837,
    'codeEtab': 326110005,
    'ecoleOrigine': 'EPP AMBOHINAMBOARINA',
    'centreExamen': 'F02/09',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 838,
    'codeEtab': 326110006,
    'ecoleOrigine': 'EPP ANARA',
    'centreExamen': 'F02/09',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 839,
    'codeEtab': 326110007,
    'ecoleOrigine': 'EPP ANDASINDRAIVONY',
    'centreExamen': 'F02/09',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 840,
    'codeEtab': 326110008,
    'ecoleOrigine': 'EPP ANDOHARANO',
    'centreExamen': 'F02/09',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 841,
    'codeEtab': 326110009,
    'ecoleOrigine': 'EPP ANDRAIDODO',
    'centreExamen': 'F02/09',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 842,
    'codeEtab': 326110002,
    'ecoleOrigine': 'EPP ANDRANOBE',
    'centreExamen': 'F02/09',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 843,
    'codeEtab': 326110002,
    'ecoleOrigine': 'EPP ANDRANOBE',
    'centreExamen': 'F02/09',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 844,
    'codeEtab': 326110012,
    'ecoleOrigine': 'EPP SANDRANATA',
    'centreExamen': 'F02/09',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 845,
    'codeEtab': 326110013,
    'ecoleOrigine': 'EPP TANAMBAO',
    'centreExamen': 'F02/09',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 846,
    'codeEtab': 326110014,
    'ecoleOrigine': 'EPP TSARAMANDROSO',
    'centreExamen': 'F02/09',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 847,
    'codeEtab': 326030010,
    'ecoleOrigine': 'EPP AMBOHIDRAKANGA',
    'centreExamen': 'F02/13',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 848,
    'codeEtab': 326031023,
    'ecoleOrigine': 'BEFARIA FIRAISANTSOA ECOLE PRIVEE LUTHERIENNE',
    'centreExamen': 'F02/13',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 849,
    'codeEtab': 326999901,
    'ecoleOrigine': 'CANDIDAT LIBRE',
    'centreExamen': 'F02/13',
    'secteur': 'LIBRE',
  },
  {
    'codeEcoleOrigine': 850,
    'codeEtab': 326031021,
    'ecoleOrigine': 'ECOLE NON CONFESSIONNELLE RATOMANAGNARIVO',
    'centreExamen': 'F02/13',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 851,
    'codeEtab': 326031001,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE AMBALAMAHATSINJO',
    'centreExamen': 'F02/13',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 852,
    'codeEtab': 326031002,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE AMBALAMISAONY',
    'centreExamen': 'F02/13',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 853,
    'codeEtab': 326031020,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE AMBALATSILA',
    'centreExamen': 'F02/13',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 854,
    'codeEtab': 326031003,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE AMBALAVAO TATAO',
    'centreExamen': 'F02/13',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 855,
    'codeEtab': 326031004,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE AMBATOVORY',
    'centreExamen': 'F02/13',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 856,
    'codeEtab': 326031005,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE ANKARITSIANANANA',
    'centreExamen': 'F02/13',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 857,
    'codeEtab': 326031006,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE ANKERANA SOMAINA',
    'centreExamen': 'F02/13',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 858,
    'codeEtab': 326031007,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE FO MASIN\'I JESOA ANTSANGY',
    'centreExamen': 'F02/13',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 859,
    'codeEtab': 326031008,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE IKOLO',
    'centreExamen': 'F02/13',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 860,
    'codeEtab': 326031013,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE SAINT FAMILLE TAMBOHOANIVO',
    'centreExamen': 'F02/13',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 861,
    'codeEtab': 326031009,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE SAINT MICHEL',
    'centreExamen': 'F02/13',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 862,
    'codeEtab': 326031010,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE SAINT PAUL IKALAVAO',
    'centreExamen': 'F02/13',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 863,
    'codeEtab': 326031019,
    'ecoleOrigine':
        'ECOLE PRIVEE CATHOLIQUE SAINTE JEANNE D\\\'ARC VOHIHAMBANA',
    'centreExamen': 'F02/13',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 864,
    'codeEtab': 326031011,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE SAINTSOA',
    'centreExamen': 'F02/13',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 865,
    'codeEtab': 326031012,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE ST JOSEPH SIRAO',
    'centreExamen': 'F02/13',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 866,
    'codeEtab': 326031022,
    'ecoleOrigine': 'ECOLE PRIVEE COTHOLIQUE TANAMBAO SAHAVANANA',
    'centreExamen': 'F02/13',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 867,
    'codeEtab': 326031026,
    'ecoleOrigine': 'ECOLE PRIVEE FANEVA',
    'centreExamen': 'F02/13',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 868,
    'codeEtab': 326031016,
    'ecoleOrigine': 'ECOLE PRIVEE FJKM ANDROMIVATO',
    'centreExamen': 'F02/13',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 869,
    'codeEtab': 326030003,
    'ecoleOrigine': 'EPP AMBALALEHIBE',
    'centreExamen': 'F02/13',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 870,
    'codeEtab': 326030004,
    'ecoleOrigine': 'EPP AMBALAMAHAMASINA',
    'centreExamen': 'F02/13',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 871,
    'codeEtab': 326030019,
    'ecoleOrigine': 'EPP AMBALAMAHARAVO',
    'centreExamen': 'F02/13',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 872,
    'codeEtab': 326060025,
    'ecoleOrigine': 'EPP AMBALAMARINA',
    'centreExamen': 'F02/13',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 873,
    'codeEtab': 326030020,
    'ecoleOrigine': 'EPP AMBALAMIJEA',
    'centreExamen': 'F02/13',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 874,
    'codeEtab': 326030005,
    'ecoleOrigine': 'EPP AMBALANIERANA',
    'centreExamen': 'F02/13',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 875,
    'codeEtab': 326030006,
    'ecoleOrigine': 'EPP AMBALAVAO I',
    'centreExamen': 'F02/13',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 876,
    'codeEtab': 326030007,
    'ecoleOrigine': 'EPP AMBALAVAOKELY',
    'centreExamen': 'F02/13',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 877,
    'codeEtab': 326030008,
    'ecoleOrigine': 'EPP AMBODIRANOMAITSO',
    'centreExamen': 'F02/13',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 878,
    'codeEtab': 326030009,
    'ecoleOrigine': 'EPP AMBOHIBOLAMENA',
    'centreExamen': 'F02/13',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 879,
    'codeEtab': 326030021,
    'ecoleOrigine': 'EPP AMBONDRONA',
    'centreExamen': 'F02/13',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 880,
    'codeEtab': 326030011,
    'ecoleOrigine': 'EPP ANDRANOVORIVATO',
    'centreExamen': 'F02/13',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 881,
    'codeEtab': 326030012,
    'ecoleOrigine': 'EPP ANDREANAVO',
    'centreExamen': 'F02/13',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 882,
    'codeEtab': 326030013,
    'ecoleOrigine': 'EPP ANKAZO',
    'centreExamen': 'F02/13',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 883,
    'codeEtab': 326030014,
    'ecoleOrigine': 'EPP ANORAMITSIPIKA',
    'centreExamen': 'F02/13',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 884,
    'codeEtab': 326030015,
    'ecoleOrigine': 'EPP ANTSANGY',
    'centreExamen': 'F02/13',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 885,
    'codeEtab': 326030026,
    'ecoleOrigine': 'EPP FIVOARANA',
    'centreExamen': 'F02/13',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 886,
    'codeEtab': 326030016,
    'ecoleOrigine': 'EPP IVORY',
    'centreExamen': 'F02/13',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 887,
    'codeEtab': 326030017,
    'ecoleOrigine': 'EPP MANINANIVO',
    'centreExamen': 'F02/13',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 888,
    'codeEtab': 326030018,
    'ecoleOrigine': 'EPP TAMBOHOMANDREVO',
    'centreExamen': 'F02/13',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 889,
    'codeEtab': 326080006,
    'ecoleOrigine': 'EPP AMBOHIBORY AVARADRANO',
    'centreExamen': 'F02/16',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 890,
    'codeEtab': 326080007,
    'ecoleOrigine': 'EPP AMBONDRONA MANEVA',
    'centreExamen': 'F02/16',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 891,
    'codeEtab': 326100008,
    'ecoleOrigine': 'EPP IALADALANGY',
    'centreExamen': 'F02/16',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 892,
    'codeEtab': 326100013,
    'ecoleOrigine': 'EPP MAROVORY',
    'centreExamen': 'F02/16',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 893,
    'codeEtab': 326999901,
    'ecoleOrigine': 'CANDIDAT LIBRE',
    'centreExamen': 'F02/16',
    'secteur': 'LIBRE',
  },
  {
    'codeEcoleOrigine': 894,
    'codeEtab': 326081001,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE AMBALAVAO ANKAZOTANA',
    'centreExamen': 'F02/16',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 895,
    'codeEtab': 326081002,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE AMPASIMBE',
    'centreExamen': 'F02/16',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 896,
    'codeEtab': 326081003,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE ST JOSEPH AMBALAMENA',
    'centreExamen': 'F02/16',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 897,
    'codeEtab': 326121002,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE TANAMBAO',
    'centreExamen': 'F02/16',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 898,
    'codeEtab': 326081004,
    'ecoleOrigine': 'ECOLE PRIVEE LA RACINE',
    'centreExamen': 'F02/16',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 899,
    'codeEtab': 326120003,
    'ecoleOrigine': 'EPP AMBALAKINANA',
    'centreExamen': 'F02/16',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 900,
    'codeEtab': 326080002,
    'ecoleOrigine': 'EPP AMBALAMENA',
    'centreExamen': 'F02/16',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 901,
    'codeEtab': 326080004,
    'ecoleOrigine': 'EPP AMBALAVAO MANEVA',
    'centreExamen': 'F02/16',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 902,
    'codeEtab': 326080003,
    'ecoleOrigine': 'EPP AMBALAVATO EST',
    'centreExamen': 'F02/16',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 903,
    'codeEtab': 326080005,
    'ecoleOrigine': 'EPP AMBALAVOLA',
    'centreExamen': 'F02/16',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 904,
    'codeEtab': 326080008,
    'ecoleOrigine': 'EPP ANKAZOTANA',
    'centreExamen': 'F02/16',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 905,
    'codeEtab': 326140011,
    'ecoleOrigine': 'EPP SAMBOHOVA',
    'centreExamen': 'F02/17',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 906,
    'codeEtab': 326141007,
    'ecoleOrigine': 'ECOLE PRIVEE  RAINISOALAMBO VATOFOTSY',
    'centreExamen': 'F02/17',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 907,
    'codeEtab': 326141001,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE AMBOASARIMARO',
    'centreExamen': 'F02/17',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 908,
    'codeEtab': 326141002,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE AMPANDRAMBATO I',
    'centreExamen': 'F02/17',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 909,
    'codeEtab': 326141004,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE SAMBOHOVA',
    'centreExamen': 'F02/17',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 910,
    'codeEtab': 326141005,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE VOHITRAFENO',
    'centreExamen': 'F02/17',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 911,
    'codeEtab': 326141006,
    'ecoleOrigine': 'ECOLE PRIVEE FJKM AMBALAMAHAZOANONY',
    'centreExamen': 'F02/17',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 912,
    'codeEtab': 326140002,
    'ecoleOrigine': 'EPP AMBALAHAMBANA',
    'centreExamen': 'F02/17',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 913,
    'codeEtab': 326140002,
    'ecoleOrigine': 'EPP AMBALAHAMBANA',
    'centreExamen': 'F02/17',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 914,
    'codeEtab': 326140003,
    'ecoleOrigine': 'EPP AMBALAMISAOTRA',
    'centreExamen': 'F02/17',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 915,
    'codeEtab': 326140004,
    'ecoleOrigine': 'EPP AMBALAVAO',
    'centreExamen': 'F02/17',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 916,
    'codeEtab': 326140005,
    'ecoleOrigine': 'EPP AMBOHIMALAZA',
    'centreExamen': 'F02/17',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 917,
    'codeEtab': 326140006,
    'ecoleOrigine': 'EPP AMBOHINAMBOARINA',
    'centreExamen': 'F02/17',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 918,
    'codeEtab': 326140007,
    'ecoleOrigine': 'EPP ANDOMOTRA',
    'centreExamen': 'F02/17',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 919,
    'codeEtab': 326140008,
    'ecoleOrigine': 'EPP ANJOZOROKELY',
    'centreExamen': 'F02/17',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 920,
    'codeEtab': 326140009,
    'ecoleOrigine': 'EPP IALAMARINA',
    'centreExamen': 'F02/17',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 921,
    'codeEtab': 326140010,
    'ecoleOrigine': 'EPP MAROTAVY AMBOHIPIAFANANA',
    'centreExamen': 'F02/17',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 922,
    'codeEtab': 326140015,
    'ecoleOrigine': 'EPP VOHITSOA',
    'centreExamen': 'F02/17',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 923,
    'codeEtab': 326999901,
    'ecoleOrigine': 'CANDIDAT LIBRE',
    'centreExamen': 'F02/24',
    'secteur': 'LIBRE',
  },
  {
    'codeEcoleOrigine': 924,
    'codeEtab': 326021018,
    'ecoleOrigine': 'COLLEGE  PRIVE MANAOSOA MAROHADY',
    'centreExamen': 'F02/24',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 925,
    'codeEtab': 326020025,
    'ecoleOrigine': 'ECOLE COMMUNAUTAIRE LOVASOA IKONGO',
    'centreExamen': 'F02/24',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 926,
    'codeEtab': 326020016,
    'ecoleOrigine': 'ECOLE COMMUNAUTAIRE SOANIERANA',
    'centreExamen': 'F02/24',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 927,
    'codeEtab': 326021001,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE AMPANOSARA',
    'centreExamen': 'F02/24',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 928,
    'codeEtab': 326021002,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE ANDRANOBE',
    'centreExamen': 'F02/24',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 929,
    'codeEtab': 326021019,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE ANDRANOMBAO',
    'centreExamen': 'F02/24',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 930,
    'codeEtab': 326021004,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE FANILO MANAOVASOA',
    'centreExamen': 'F02/24',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 931,
    'codeEtab': 326021011,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE RANOMENA',
    'centreExamen': 'F02/24',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 932,
    'codeEtab': 326021013,
    'ecoleOrigine':
        'ECOLE PRIVEE CATHOLIQUE SAINTE THERESE DE L\\\'ENFANT JESUS MAGNEVA ANTARATANA',
    'centreExamen': 'F02/24',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 933,
    'codeEtab': 326021005,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE ST BENOIT AMPIANA',
    'centreExamen': 'F02/24',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 934,
    'codeEtab': 326021006,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE TANITSIHOMEHY A',
    'centreExamen': 'F02/24',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 935,
    'codeEtab': 326021007,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE TANJOMBE',
    'centreExamen': 'F02/24',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 936,
    'codeEtab': 326021017,
    'ecoleOrigine': 'ECOLE PRIVEE FJKM ITARATANA',
    'centreExamen': 'F02/24',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 937,
    'codeEtab': 326021010,
    'ecoleOrigine': 'ECOLE PRIVEE LUTHERIENNE SOANIERANA TETEZANTANY',
    'centreExamen': 'F02/24',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 938,
    'codeEtab': 326030010,
    'ecoleOrigine': 'EPP AMBOHIDRAKANGA',
    'centreExamen': 'F02/24',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 939,
    'codeEtab': 326020004,
    'ecoleOrigine': 'EPP AMBONIREANA',
    'centreExamen': 'F02/24',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 940,
    'codeEtab': 326020005,
    'ecoleOrigine': 'EPP ANDRALASENDRY',
    'centreExamen': 'F02/24',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 941,
    'codeEtab': 326020006,
    'ecoleOrigine': 'EPP ANDRANOMIDITRA CENTRALE',
    'centreExamen': 'F02/24',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 942,
    'codeEtab': 326020008,
    'ecoleOrigine': 'EPP ANDREANA SOAMIAFARA',
    'centreExamen': 'F02/24',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 943,
    'codeEtab': 326020009,
    'ecoleOrigine': 'EPP COMMUNAUTAIRE BETAFO',
    'centreExamen': 'F02/24',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 944,
    'codeEtab': 326020003,
    'ecoleOrigine': 'EPP FANIRIANTSOA',
    'centreExamen': 'F02/24',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 945,
    'codeEtab': 326020010,
    'ecoleOrigine': 'EPP MAMARINA TSILEONDAHY',
    'centreExamen': 'F02/24',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 946,
    'codeEtab': 326020015,
    'ecoleOrigine': 'EPP SERANANA VOHIBATO',
    'centreExamen': 'F02/24',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 947,
    'codeEtab': 326020011,
    'ecoleOrigine': 'EPP SOAMIAFARA TANITSIHOMEHY',
    'centreExamen': 'F02/24',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 948,
    'codeEtab': 326020012,
    'ecoleOrigine': 'EPP TIANAKANGA',
    'centreExamen': 'F02/24',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 949,
    'codeEtab': 326020013,
    'ecoleOrigine': 'EPP TOMARA',
    'centreExamen': 'F02/24',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 950,
    'codeEtab': 326020014,
    'ecoleOrigine': 'EPP TSARAFIDY BEMANGEVITRA',
    'centreExamen': 'F02/24',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 951,
    'codeEtab': 326130002,
    'ecoleOrigine': 'EPP AMBAIBO',
    'centreExamen': 'F02/25',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 952,
    'codeEtab': 326130004,
    'ecoleOrigine': 'EPP AMBALATSIAFAKOMBY',
    'centreExamen': 'F02/25',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 953,
    'codeEtab': 326130007,
    'ecoleOrigine': 'EPP AMBOAVONANA',
    'centreExamen': 'F02/25',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 954,
    'codeEtab': 326130009,
    'ecoleOrigine': 'EPP ANJA LAMOSINA',
    'centreExamen': 'F02/25',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 955,
    'codeEtab': 326130016,
    'ecoleOrigine': 'EPP MAHAFALY',
    'centreExamen': 'F02/25',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 956,
    'codeEtab': 326130017,
    'ecoleOrigine': 'EPP MIARAMANDROSO',
    'centreExamen': 'F02/25',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 957,
    'codeEtab': 326999901,
    'ecoleOrigine': 'CANDIDAT LIBRE',
    'centreExamen': 'F02/25',
    'secteur': 'LIBRE',
  },
  {
    'codeEcoleOrigine': 958,
    'codeEtab': 326131027,
    'ecoleOrigine': 'COLLEGE SAINT FRANCOIS XAVIER AMBATOLAHY',
    'centreExamen': 'F02/25',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 959,
    'codeEtab': 326160001,
    'ecoleOrigine': 'ECOLE COMMUNAUTAIRE AMPEMBY',
    'centreExamen': 'F02/25',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 960,
    'codeEtab': 326130024,
    'ecoleOrigine': 'ECOLE COMMUNAUTAIRE BESOARAVY',
    'centreExamen': 'F02/25',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 961,
    'codeEtab': 326130029,
    'ecoleOrigine': 'ECOLE COMMUNAUTAIRE IKINA',
    'centreExamen': 'F02/25',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 962,
    'codeEtab': 326130027,
    'ecoleOrigine': 'ECOLE COMMUNAUTAIRE MANAITSA',
    'centreExamen': 'F02/25',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 963,
    'codeEtab': 326130026,
    'ecoleOrigine': 'ECOLE COMMUNAUTAIRE SOMONDRANO',
    'centreExamen': 'F02/25',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 964,
    'codeEtab': 326130028,
    'ecoleOrigine': 'ECOLE COMMUNAUTAIRE TSARATANANA',
    'centreExamen': 'F02/25',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 965,
    'codeEtab': 326131025,
    'ecoleOrigine': 'ECOLE NON COFESSIONNELLE ATRIKA BEAPOMBO',
    'centreExamen': 'F02/25',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 966,
    'codeEtab': 326131022,
    'ecoleOrigine': 'ECOLE NON CONFESSIONELLE EZAKA  A MATSIATRA',
    'centreExamen': 'F02/25',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 967,
    'codeEtab': 326131001,
    'ecoleOrigine': 'ECOLE NON CONFESSIONNELLE FIOMBONANTSOA TOZEKA',
    'centreExamen': 'F02/25',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 968,
    'codeEtab': 326131032,
    'ecoleOrigine': 'ECOLE NON CONFESSIONNELLE FITIAVANA LAMOSINA',
    'centreExamen': 'F02/25',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 969,
    'codeEtab': 326131004,
    'ecoleOrigine': 'ECOLE PRIVEE ANTSAHABE TANIDITRA',
    'centreExamen': 'F02/25',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 970,
    'codeEtab': 326131011,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE  IJOBO',
    'centreExamen': 'F02/25',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 972,
    'codeEtab': 326131005,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE AMBALATELO',
    'centreExamen': 'F02/25',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 973,
    'codeEtab': 326131006,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE AMBALAVAO LAZAINARIVO',
    'centreExamen': 'F02/25',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 974,
    'codeEtab': 326131007,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE AMBATANDRANO',
    'centreExamen': 'F02/25',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 975,
    'codeEtab': 326131008,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE AMBATOHARANANA',
    'centreExamen': 'F02/25',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 976,
    'codeEtab': 326131010,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE AMBOAVONA',
    'centreExamen': 'F02/25',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 977,
    'codeEtab': 326131003,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE FOMADION\'I MARIA LAMOSINA',
    'centreExamen': 'F02/25',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 980,
    'codeEtab': 326131012,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE IAVONIMANANA',
    'centreExamen': 'F02/25',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 981,
    'codeEtab': 326131029,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE LAVAHATSARA',
    'centreExamen': 'F02/25',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 982,
    'codeEtab': 326131006,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE LAZAINARIVO',
    'centreExamen': 'F02/25',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 983,
    'codeEtab': 326131013,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE MAHASILA',
    'centreExamen': 'F02/25',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 984,
    'codeEtab': 326131028,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE MORARANO',
    'centreExamen': 'F02/25',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 985,
    'codeEtab': 326131014,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE REANDAVA',
    'centreExamen': 'F02/25',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 986,
    'codeEtab': 326131015,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE TAMBOHOANIVO',
    'centreExamen': 'F02/25',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 987,
    'codeEtab': 326131030,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE TAMBOHOBE',
    'centreExamen': 'F02/25',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 988,
    'codeEtab': 326131016,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE TEAROMIZAHA',
    'centreExamen': 'F02/25',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 989,
    'codeEtab': 326131031,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE VATOBE AMBAIBO',
    'centreExamen': 'F02/25',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 990,
    'codeEtab': 326131017,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE VOATAVOLEMAKA',
    'centreExamen': 'F02/25',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 991,
    'codeEtab': 326131019,
    'ecoleOrigine': 'ECOLE PRIVEE PROTESTANTE LOHOMBY',
    'centreExamen': 'F02/25',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 992,
    'codeEtab': 326131021,
    'ecoleOrigine': 'ECOLE PROTESTANTE FANANTENANA',
    'centreExamen': 'F02/25',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 993,
    'codeEtab': 326130025,
    'ecoleOrigine': 'ECOLECOMMUNAUTAIRE FOPOHONY',
    'centreExamen': 'F02/25',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 994,
    'codeEtab': 326130003,
    'ecoleOrigine': 'EPP AMBALAMANANDRAY',
    'centreExamen': 'F02/25',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 995,
    'codeEtab': 326130005,
    'ecoleOrigine': 'EPP AMBALAVAO LAZAINARIVO',
    'centreExamen': 'F02/25',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 996,
    'codeEtab': 326130006,
    'ecoleOrigine': 'EPP AMBATOHARANANA VAOLAHY',
    'centreExamen': 'F02/25',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 997,
    'codeEtab': 326130008,
    'ecoleOrigine': 'EPP ANAKASANA VAOLAHY',
    'centreExamen': 'F02/25',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 998,
    'codeEtab': 326130022,
    'ecoleOrigine': 'EPP ANDRANONDRAIKITRA',
    'centreExamen': 'F02/25',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 999,
    'codeEtab': 326130010,
    'ecoleOrigine': 'EPP ANJANOMALAZA',
    'centreExamen': 'F02/25',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 1000,
    'codeEtab': 326130011,
    'ecoleOrigine': 'EPP ANOTSIMAINTY',
    'centreExamen': 'F02/25',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 1002,
    'codeEtab': 326130012,
    'ecoleOrigine': 'EPP BESOA',
    'centreExamen': 'F02/25',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 1003,
    'codeEtab': 326130013,
    'ecoleOrigine': 'EPP ITSIFO',
    'centreExamen': 'F02/25',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 1004,
    'codeEtab': 326130014,
    'ecoleOrigine': 'EPP IVORY TSIFO',
    'centreExamen': 'F02/25',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 1005,
    'codeEtab': 326130015,
    'ecoleOrigine': 'EPP LAMOSINA VOHIMARINA',
    'centreExamen': 'F02/25',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 1006,
    'codeEtab': 326130018,
    'ecoleOrigine': 'EPP SOARANO ANJA',
    'centreExamen': 'F02/25',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 1007,
    'codeEtab': 326130019,
    'ecoleOrigine': 'EPP TAMBOHOANIVO',
    'centreExamen': 'F02/25',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 1008,
    'codeEtab': 326130023,
    'ecoleOrigine': 'EPP TANAMBAO',
    'centreExamen': 'F02/25',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 1009,
    'codeEtab': 326130020,
    'ecoleOrigine': 'EPP VOATAVOLEMAKA',
    'centreExamen': 'F02/25',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 1010,
    'codeEtab': 326130021,
    'ecoleOrigine': 'EPP VOHIMARINA',
    'centreExamen': 'F02/25',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 1011,
    'codeEtab': 326051002,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE AMBOHIMARANITRA',
    'centreExamen': 'F02/31',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 1012,
    'codeEtab': 326051007,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE AMBOLO',
    'centreExamen': 'F02/31',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 1013,
    'codeEtab': 326021002,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE ANDRANOBE',
    'centreExamen': 'F02/31',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 1014,
    'codeEtab': 326021006,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE TANITSIHOMEHY A',
    'centreExamen': 'F02/31',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 1015,
    'codeEtab': 326050004,
    'ecoleOrigine': 'EPP AMBALAVAO SOATSIHAVELA',
    'centreExamen': 'F02/31',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 1016,
    'codeEtab': 326050005,
    'ecoleOrigine': 'EPP AMBOHIBORY MAHASOA',
    'centreExamen': 'F02/31',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 1017,
    'codeEtab': 326050006,
    'ecoleOrigine': 'EPP AMBOHIMARANITRA',
    'centreExamen': 'F02/31',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 1018,
    'codeEtab': 326050007,
    'ecoleOrigine': 'EPP IHAZOARA',
    'centreExamen': 'F02/31',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 1019,
    'codeEtab': 326050008,
    'ecoleOrigine': 'EPP IKILIVIA',
    'centreExamen': 'F02/31',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 1020,
    'codeEtab': 326050012,
    'ecoleOrigine': 'EPP MANGARIVOTRA',
    'centreExamen': 'F02/31',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 1021,
    'codeEtab': 326050009,
    'ecoleOrigine': 'EPP MANOVOSOA',
    'centreExamen': 'F02/31',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 1022,
    'codeEtab': 326050010,
    'ecoleOrigine': 'EPP NANADREANA',
    'centreExamen': 'F02/31',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 1023,
    'codeEtab': 326050011,
    'ecoleOrigine': 'EPP SOAMIRAIHINA',
    'centreExamen': 'F02/31',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 1024,
    'codeEtab': 326050013,
    'ecoleOrigine': 'EPP TSARAFIDY',
    'centreExamen': 'F02/31',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 1025,
    'codeEtab': 326091004,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE AMPAMAREMANA',
    'centreExamen': 'F02/35',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 1026,
    'codeEtab': 326091002,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE FO MASIN I JESOA',
    'centreExamen': 'F02/35',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 1027,
    'codeEtab': 326091002,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE FO MASIN\\\'I JESOA',
    'centreExamen': 'F02/35',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 1028,
    'codeEtab': 326091003,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE ST DONATIEN AMBONDRONA',
    'centreExamen': 'F02/35',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 1029,
    'codeEtab': 326091003,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE ST DONATIEN AMBONDRONA',
    'centreExamen': 'F02/35',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 1030,
    'codeEtab': 326101009,
    'ecoleOrigine': 'ECOLE PRIVEE FLM FANANTENANA LANGELA',
    'centreExamen': 'F02/35',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 1031,
    'codeEtab': 326101009,
    'ecoleOrigine': 'ECOLE PRIVEE FLM LANGELA FANANTENANA',
    'centreExamen': 'F02/35',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 1032,
    'codeEtab': 326090001,
    'ecoleOrigine': 'EPP AMBALAMITSINJONY',
    'centreExamen': 'F02/35',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 1033,
    'codeEtab': 326090002,
    'ecoleOrigine': 'EPP ANKERANA OUEST',
    'centreExamen': 'F02/35',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 1034,
    'codeEtab': 326110023,
    'ecoleOrigine': 'EPP MANANTENASOA',
    'centreExamen': 'F02/35',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 1035,
    'codeEtab': 326090003,
    'ecoleOrigine': 'EPP SAHAMENA',
    'centreExamen': 'F02/35',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 1036,
    'codeEtab': 326090004,
    'ecoleOrigine': 'EPP SOAINDRANA',
    'centreExamen': 'F02/35',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 1037,
    'codeEtab': 326999901,
    'ecoleOrigine': 'CANDIDAT LIBRE',
    'centreExamen': 'F02/38',
    'secteur': 'LIBRE',
  },
  {
    'codeEcoleOrigine': 1038,
    'codeEtab': 326041004,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE ASANA VATOMITANTANA',
    'centreExamen': 'F02/38',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 1039,
    'codeEtab': 326041001,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE ZARABE FANAMEANA',
    'centreExamen': 'F02/38',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 1040,
    'codeEtab': 326040001,
    'ecoleOrigine': 'EPP AMBOHIBORY III',
    'centreExamen': 'F02/38',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 1041,
    'codeEtab': 326060010,
    'ecoleOrigine': 'EPP ANTSIHARA',
    'centreExamen': 'F02/38',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 1042,
    'codeEtab': 326040002,
    'ecoleOrigine': 'EPP ASANA VATOMITANTANA',
    'centreExamen': 'F02/38',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 1043,
    'codeEtab': 326040003,
    'ecoleOrigine': 'EPP FANAMEANA AMBATOHARANANA',
    'centreExamen': 'F02/38',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 1044,
    'codeEtab': 326040004,
    'ecoleOrigine': 'EPP FANAMEANA SOALOZOKA',
    'centreExamen': 'F02/38',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 1045,
    'codeEtab': 326040005,
    'ecoleOrigine': 'EPP IHAFADRAY',
    'centreExamen': 'F02/38',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 1046,
    'codeEtab': 326120004,
    'ecoleOrigine': 'EPP AMBALATANIFOTSY',
    'centreExamen': 'F02/39',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 1047,
    'codeEtab': 326120005,
    'ecoleOrigine': 'EPP AMBY',
    'centreExamen': 'F02/39',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 1048,
    'codeEtab': 326120006,
    'ecoleOrigine': 'EPP ANDOHAMANDRANOMAVO',
    'centreExamen': 'F02/39',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 1049,
    'codeEtab': 326120007,
    'ecoleOrigine': 'EPP ANTSIOBE',
    'centreExamen': 'F02/39',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 1050,
    'codeEtab': 326120010,
    'ecoleOrigine': 'EPP TSIANESENA',
    'centreExamen': 'F02/39',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 1051,
    'codeEtab': 326121002,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE TANAMBAO',
    'centreExamen': 'F02/39',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 1052,
    'codeEtab': 326120003,
    'ecoleOrigine': 'EPP AMBALAKINANA',
    'centreExamen': 'F02/39',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 1053,
    'codeEtab': 326120008,
    'ecoleOrigine': 'EPP TAMBOHOBE',
    'centreExamen': 'F02/39',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 1054,
    'codeEtab': 326151002,
    'ecoleOrigine': 'ECOLE PRIVE CATHOLIQUE TAMBOHOBE II',
    'centreExamen': 'F02/50',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 1055,
    'codeEtab': 326061009,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE SOATANANA',
    'centreExamen': 'F02/50',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 1056,
    'codeEtab': 326010006,
    'ecoleOrigine': 'EPP AMBALATAVY',
    'centreExamen': 'F02/50',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 1057,
    'codeEtab': 326060006,
    'ecoleOrigine': 'EPP AMBATOTERAKA',
    'centreExamen': 'F02/50',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 1058,
    'codeEtab': 326060010,
    'ecoleOrigine': 'EPP ANTSIHARA',
    'centreExamen': 'F02/50',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 1059,
    'codeEtab': 326060011,
    'ecoleOrigine': 'EPP MANAMISOA',
    'centreExamen': 'F02/50',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 1060,
    'codeEtab': 326060013,
    'ecoleOrigine': 'EPP SOATANANA ANDASY',
    'centreExamen': 'F02/50',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 1061,
    'codeEtab': 326060017,
    'ecoleOrigine': 'EPP TSITARY',
    'centreExamen': 'F02/50',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 1062,
    'codeEtab': 326060025,
    'ecoleOrigine': 'ECOLE COMMUNAUTAIRE AMBALAMARINA SANDRANATA',
    'centreExamen': 'F02/01',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 1063,
    'codeEtab': 326110037,
    'ecoleOrigine': 'ECOLE COMMUNAUTAIRE ANDRANOHERANA',
    'centreExamen': 'F02/09',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 1064,
    'codeEtab': 326020007,
    'ecoleOrigine': 'EPP ANDREANA VOHIBATO',
    'centreExamen': 'F02/24',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 1065,
    'codeEtab': 326151001,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE JEAN BOSCO TAMBOHOMANDREVO',
    'centreExamen': 'F02/50',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 1066,
    'codeEtab': 326150201,
    'ecoleOrigine': 'ECOLE COMMUNAUTAIRE AMBALAMARINA',
    'centreExamen': 'F02/50',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 1067,
    'codeEtab': 326030020,
    'ecoleOrigine': 'EPP AMBALAMIJEA',
    'centreExamen': 'F02/50',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 1068,
    'codeEtab': 326130033,
    'ecoleOrigine': 'ECOLE COMMUNAUTAIRE VOENANA',
    'centreExamen': 'F02/25',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 1069,
    'codeEtab': 326021015,
    'ecoleOrigine': 'ECOLE PRIVE CATHOLIQUE VOHIBATO',
    'centreExamen': 'F02/24',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 1070,
    'codeEtab': 326020016,
    'ecoleOrigine': 'EPP SOANIERANA',
    'centreExamen': 'F02/24',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 1071,
    'codeEtab': 326021027,
    'ecoleOrigine': 'ECOLE PRIVE CATHOLIQUE ANTARAMBIBY',
    'centreExamen': 'F02/24',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 1072,
    'codeEtab': 326021301,
    'ecoleOrigine': 'ECOLE PRIVE CATHOLIQUE AMPISAORANA',
    'centreExamen': 'F02/24',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 1073,
    'codeEtab': 326121003,
    'ecoleOrigine': 'ECOLE PRIVE CATHOLIQUE AMBODITANJONA',
    'centreExamen': 'F02/39',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 1074,
    'codeEtab': 326031601,
    'ecoleOrigine': 'ECOLE COMMUNAUTAIRE ILANITRA',
    'centreExamen': 'F02/13',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 1075,
    'codeEtab': 326031013,
    'ecoleOrigine': 'ECOLE PRIVE CATHOLIQUE TAMBOHOANIVO',
    'centreExamen': 'F02/13',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 1076,
    'codeEtab': 326080601,
    'ecoleOrigine': 'ECOLE PRIVEE LUTHERIENNE NAMANA ANKERANA',
    'centreExamen': 'F02/16',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 1077,
    'codeEtab': 326101009,
    'ecoleOrigine': 'ECOLE COMMUNAUTAIRE AMPAMAREMANA',
    'centreExamen': 'F02/35',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 1078,
    'codeEtab': 326130032,
    'ecoleOrigine': 'ECOLE COMMUNAUTAIRE SAKAMANANA',
    'centreExamen': 'F02/25',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 1079,
    'codeEtab': 326071701,
    'ecoleOrigine': 'ECOLE COMMUNAUTAIRE VOHIMARINA',
    'centreExamen': 'F02/07',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 1080,
    'codeEtab': 326050501,
    'ecoleOrigine': 'ECOLE PRIVE CATHOLIQUE AMBATOBE',
    'centreExamen': 'F02/31',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 1081,
    'codeEtab': 326100020,
    'ecoleOrigine': 'EPP VOHIDROA',
    'centreExamen': 'F02/08',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 1082,
    'codeEtab': 326021018,
    'ecoleOrigine': 'COLLEGE PRIVE MANAOSOA MAROHADY',
    'centreExamen': 'F02/24',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 1083,
    'codeEtab': 326021018,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE SAINT BENOIT AMPIANA',
    'centreExamen': 'F02/24',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 1084,
    'codeEtab': 326021005,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE SAINT BENOIT AMPIANA',
    'centreExamen': 'F02/24',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 1085,
    'codeEtab': 326020023,
    'ecoleOrigine': 'EPP BETAFO',
    'centreExamen': 'F02/24',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 1086,
    'codeEtab': 326020026,
    'ecoleOrigine': 'ECOLE COMMUNAUTAIRE FIVOARANTSOA RANOMENA',
    'centreExamen': 'F02/24',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 1087,
    'codeEtab': 326021008,
    'ecoleOrigine': 'ECOLE PRIVEE CATHOLIQUE SAINT CHARLES TSARAMANDROSO',
    'centreExamen': 'F02/24',
    'secteur': 'PRIVE',
  },
  {
    'codeEcoleOrigine': 1088,
    'codeEtab': 326060601,
    'ecoleOrigine': 'ECOLE COMMUNAUTAIRE MAZAVASOA',
    'centreExamen': 'F02/01',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 1089,
    'codeEtab': 326100020,
    'ecoleOrigine': 'EPP VOHIDROA',
    'centreExamen': 'F02/08',
    'secteur': 'PUBLIC',
  },
  {
    'codeEcoleOrigine': 1090,
    'codeEtab': 326999901,
    'ecoleOrigine': 'CANDIDAT LIBRE',
    'centreExamen': 'F02/02',
    'secteur': 'LIBRE',
  },
];
