/// Liste complète des établissements (feuille 'Liste Etab').
/// codeSecteur : 0 = Public, 1 = Privé (à confirmer), zap = zone d'appartenance
/// Généré depuis stageCisco.xlsx — 366 entrées.
const List<Map<String, dynamic>> listeEtablissements = [
  {
    'codeEtab': 326020302,
    'nomEtab': 'ECOLE COMMUNAUTAIRE LIANTSOA AMBONDRONA',
    'codeSecteur': 0,
    'zap': 'ANDRANOMIDITRA',
  },
  {
    'codeEtab': 326101010,
    'nomEtab': 'LYCEE PRIVE FANATENANA',
    'codeSecteur': 1,
    'zap': 'TALATA AMPANO',
  },
  {
    'codeEtab': 326010004,
    'nomEtab': 'EPP ALAKAMISY ITENINA',
    'codeSecteur': 0,
    'zap': 'ALAKAMISY ITENINA',
  },
  {
    'codeEtab': 326010005,
    'nomEtab': 'EPP AMBALAFAHIBATO',
    'codeSecteur': 0,
    'zap': 'ALAKAMISY ITENINA',
  },
  {
    'codeEtab': 326010006,
    'nomEtab': 'EPP AMBALATAVY',
    'codeSecteur': 0,
    'zap': 'ANJANOMANANA TSIMIAVAKA',
  },
  {
    'codeEtab': 326010007,
    'nomEtab': 'EPP ANJAMANA',
    'codeSecteur': 0,
    'zap': 'ALAKAMISY ITENINA',
  },
  {
    'codeEtab': 326010008,
    'nomEtab': 'EPP MAROSALAZANA',
    'codeSecteur': 0,
    'zap': 'ALAKAMISY ITENINA',
  },
  {
    'codeEtab': 326010009,
    'nomEtab': 'EPP MIANDRIVAO',
    'codeSecteur': 0,
    'zap': 'ALAKAMISY ITENINA',
  },
  {
    'codeEtab': 326010010,
    'nomEtab': 'EPP RIAMBARY',
    'codeSecteur': 0,
    'zap': 'ALAKAMISY ITENINA',
  },
  {
    'codeEtab': 326010011,
    'nomEtab': 'EPP SAHAVINDRANINA',
    'codeSecteur': 0,
    'zap': 'ALAKAMISY ITENINA',
  },
  {
    'codeEtab': 326010012,
    'nomEtab': 'EPP SANGASANGA NORD',
    'codeSecteur': 0,
    'zap': 'ALAKAMISY ITENINA',
  },
  {
    'codeEtab': 326010013,
    'nomEtab': 'EPP SOATSIHADINO',
    'codeSecteur': 0,
    'zap': 'ALAKAMISY ITENINA',
  },
  {
    'codeEtab': 326010014,
    'nomEtab': 'EPP TANDROKAZO',
    'codeSecteur': 0,
    'zap': 'ALAKAMISY ITENINA',
  },
  {
    'codeEtab': 326010015,
    'nomEtab': 'EPP TSILAZO LOVASOA',
    'codeSecteur': 0,
    'zap': 'ALAKAMISY ITENINA',
  },
  {
    'codeEtab': 326010016,
    'nomEtab': 'EPP VIDIAMBOLA',
    'codeSecteur': 0,
    'zap': 'ALAKAMISY ITENINA',
  },
  {
    'codeEtab': 326010021,
    'nomEtab': 'EPP TARATRA',
    'codeSecteur': 0,
    'zap': 'ALAKAMISY ITENINA',
  },
  {
    'codeEtab': 326010022,
    'nomEtab': 'EPP FANIRIANTSOA',
    'codeSecteur': 0,
    'zap': 'ALAKAMISY ITENINA',
  },
  {
    'codeEtab': 326020003,
    'nomEtab': 'EPP FANIRIANTSOA',
    'codeSecteur': 0,
    'zap': 'ANDRANOMIDITRA',
  },
  {
    'codeEtab': 326020004,
    'nomEtab': 'EPP AMBONIREANA',
    'codeSecteur': 0,
    'zap': 'ANDRANOMIDITRA',
  },
  {
    'codeEtab': 326020005,
    'nomEtab': 'EPP ANDRALASENDRY',
    'codeSecteur': 0,
    'zap': 'ANDRANOMIDITRA',
  },
  {
    'codeEtab': 326020006,
    'nomEtab': 'EPP ANDRANOMIDITRA CENTRALE',
    'codeSecteur': 0,
    'zap': 'ANDRANOMIDITRA',
  },
  {
    'codeEtab': 326020007,
    'nomEtab': 'EPP ANDREANA VOHIBATO',
    'codeSecteur': 0,
    'zap': 'ANDRANOMIDITRA',
  },
  {
    'codeEtab': 326020008,
    'nomEtab': 'EPP ANDREANA SOAMIAFARA',
    'codeSecteur': 0,
    'zap': 'ANDRANOMIDITRA',
  },
  {
    'codeEtab': 326020010,
    'nomEtab': 'EPP MAMARINA TSILEONDAHY',
    'codeSecteur': 0,
    'zap': 'ANDRANOMIDITRA',
  },
  {
    'codeEtab': 326020011,
    'nomEtab': 'EPP SOAMIAFARA TANITSIHOMEHY',
    'codeSecteur': 0,
    'zap': 'ANDRANOMIDITRA',
  },
  {
    'codeEtab': 326020012,
    'nomEtab': 'EPP TIANAKANGA',
    'codeSecteur': 0,
    'zap': 'ANDRANOMIDITRA',
  },
  {
    'codeEtab': 326020013,
    'nomEtab': 'EPP TOMARA',
    'codeSecteur': 0,
    'zap': 'ANDRANOMIDITRA',
  },
  {
    'codeEtab': 326020014,
    'nomEtab': 'EPP TSARAFIDY BEMANGEVITRA',
    'codeSecteur': 0,
    'zap': 'ANDRANOMIDITRA',
  },
  {
    'codeEtab': 326020015,
    'nomEtab': 'EPP SERANANA VOHIBATO',
    'codeSecteur': 0,
    'zap': 'ANDRANOMIDITRA',
  },
  {
    'codeEtab': 326020016,
    'nomEtab': 'EPP SOANIERANA',
    'codeSecteur': 0,
    'zap': 'ANDRANOMIDITRA',
  },
  {
    'codeEtab': 326020023,
    'nomEtab': 'EPP BETAFO',
    'codeSecteur': 0,
    'zap': 'ANDRANOMIDITRA',
  },
  {
    'codeEtab': 326020025,
    'nomEtab': 'ECOLE COMMUNAUTAIRE LOVASOA IKONGO',
    'codeSecteur': 0,
    'zap': 'ANDRANOMIDITRA',
  },
  {
    'codeEtab': 326020026,
    'nomEtab': 'ECOLE COMMUNAUTAIRE FIVOARANTSOA RANOMENA',
    'codeSecteur': 0,
    'zap': 'ANDRANOMIDITRA',
  },
  {
    'codeEtab': 326030003,
    'nomEtab': 'EPP AMBALALEHIBE',
    'codeSecteur': 0,
    'zap': 'ANDRANOVORIVATO',
  },
  {
    'codeEtab': 326030004,
    'nomEtab': 'EPP AMBALAMAHAMASINA',
    'codeSecteur': 0,
    'zap': 'ANDRANOVORIVATO',
  },
  {
    'codeEtab': 326030005,
    'nomEtab': 'EPP AMBALANIERANA',
    'codeSecteur': 0,
    'zap': 'ANDRANOVORIVATO',
  },
  {
    'codeEtab': 326030006,
    'nomEtab': 'EPP AMBALAVAO I',
    'codeSecteur': 0,
    'zap': 'ANDRANOVORIVATO',
  },
  {
    'codeEtab': 326030007,
    'nomEtab': 'EPP AMBALAVAOKELY',
    'codeSecteur': 0,
    'zap': 'ANDRANOVORIVATO',
  },
  {
    'codeEtab': 326030008,
    'nomEtab': 'EPP AMBODIRANOMAITSO',
    'codeSecteur': 0,
    'zap': 'ANDRANOVORIVATO',
  },
  {
    'codeEtab': 326030009,
    'nomEtab': 'EPP AMBOHIBOLAMENA',
    'codeSecteur': 0,
    'zap': 'ANDRANOVORIVATO',
  },
  {
    'codeEtab': 326030010,
    'nomEtab': 'EPP AMBOHIDRAKANGA',
    'codeSecteur': 0,
    'zap': 'ANDRANOVORIVATO',
  },
  {
    'codeEtab': 326030011,
    'nomEtab': 'EPP ANDRANOVORIVATO',
    'codeSecteur': 0,
    'zap': 'ANDRANOVORIVATO',
  },
  {
    'codeEtab': 326030012,
    'nomEtab': 'EPP ANDREANAVO',
    'codeSecteur': 0,
    'zap': 'ANDRANOVORIVATO',
  },
  {
    'codeEtab': 326030013,
    'nomEtab': 'EPP ANKAZO',
    'codeSecteur': 0,
    'zap': 'ANDRANOVORIVATO',
  },
  {
    'codeEtab': 326030014,
    'nomEtab': 'EPP ANORAMITSIPIKA',
    'codeSecteur': 0,
    'zap': 'ANDRANOVORIVATO',
  },
  {
    'codeEtab': 326030015,
    'nomEtab': 'EPP ANTSANGY',
    'codeSecteur': 0,
    'zap': 'ANDRANOVORIVATO',
  },
  {
    'codeEtab': 326030016,
    'nomEtab': 'EPP IVORY',
    'codeSecteur': 0,
    'zap': 'ANDRANOVORIVATO',
  },
  {
    'codeEtab': 326030017,
    'nomEtab': 'EPP MANINANIVO',
    'codeSecteur': 0,
    'zap': 'ANDRANOVORIVATO',
  },
  {
    'codeEtab': 326030018,
    'nomEtab': 'EPP TAMBOHOMANDREVO',
    'codeSecteur': 0,
    'zap': 'ANDRANOVORIVATO',
  },
  {
    'codeEtab': 326030019,
    'nomEtab': 'EPP AMBALAMAHARAVO',
    'codeSecteur': 0,
    'zap': 'ANDRANOVORIVATO',
  },
  {
    'codeEtab': 326030020,
    'nomEtab': 'EPP AMBALAMIJEA',
    'codeSecteur': 0,
    'zap': 'ANDRANOVORIVATO',
  },
  {
    'codeEtab': 326030021,
    'nomEtab': 'EPP AMBONDRONA',
    'codeSecteur': 0,
    'zap': 'ANDRANOVORIVATO',
  },
  {
    'codeEtab': 326030026,
    'nomEtab': 'EPP FIVOARANA',
    'codeSecteur': 0,
    'zap': 'ANDRANOVORIVATO',
  },
  {
    'codeEtab': 326031601,
    'nomEtab': 'ECOLE COMMUNAUTAIRE ILANITRA',
    'codeSecteur': 0,
    'zap': 'ANDRANOVORIVATO',
  },
  {
    'codeEtab': 326040001,
    'nomEtab': 'EPP AMBOHIBORY III',
    'codeSecteur': 0,
    'zap': 'ANKAROMALAZA MIFANASOA',
  },
  {
    'codeEtab': 326040002,
    'nomEtab': 'EPP ASANA VATOMITANTANA',
    'codeSecteur': 0,
    'zap': 'ANKAROMALAZA MIFANASOA',
  },
  {
    'codeEtab': 326040003,
    'nomEtab': 'EPP FANAMEANA AMBATOHARANANA',
    'codeSecteur': 0,
    'zap': 'ANKAROMALAZA MIFANASOA',
  },
  {
    'codeEtab': 326040004,
    'nomEtab': 'EPP FANAMEANA SOALOZOKA',
    'codeSecteur': 0,
    'zap': 'ANKAROMALAZA MIFANASOA',
  },
  {
    'codeEtab': 326040005,
    'nomEtab': 'EPP IHAFADRAY',
    'codeSecteur': 0,
    'zap': 'ANKAROMALAZA MIFANASOA',
  },
  {
    'codeEtab': 326050004,
    'nomEtab': 'EPP AMBALAVAO SOATSIHAVELA',
    'codeSecteur': 0,
    'zap': 'IHAZOARA',
  },
  {
    'codeEtab': 326050005,
    'nomEtab': 'EPP AMBOHIBORY MAHASOA',
    'codeSecteur': 0,
    'zap': 'IHAZOARA',
  },
  {
    'codeEtab': 326050006,
    'nomEtab': 'EPP AMBOHIMARANITRA',
    'codeSecteur': 0,
    'zap': 'IHAZOARA',
  },
  {
    'codeEtab': 326050007,
    'nomEtab': 'EPP IHAZOARA',
    'codeSecteur': 0,
    'zap': 'IHAZOARA',
  },
  {
    'codeEtab': 326050008,
    'nomEtab': 'EPP IKILIVIA',
    'codeSecteur': 0,
    'zap': 'IHAZOARA',
  },
  {
    'codeEtab': 326050009,
    'nomEtab': 'EPP MANOVOSOA',
    'codeSecteur': 0,
    'zap': 'IHAZOARA',
  },
  {
    'codeEtab': 326050010,
    'nomEtab': 'EPP NANADREANA',
    'codeSecteur': 0,
    'zap': 'IHAZOARA',
  },
  {
    'codeEtab': 326050011,
    'nomEtab': 'EPP SOAMIRAIHINA',
    'codeSecteur': 0,
    'zap': 'IHAZOARA',
  },
  {
    'codeEtab': 326050012,
    'nomEtab': 'EPP MANGARIVOTRA',
    'codeSecteur': 0,
    'zap': 'IHAZOARA',
  },
  {
    'codeEtab': 326050013,
    'nomEtab': 'EPP TSARAFIDY',
    'codeSecteur': 0,
    'zap': 'IHAZOARA',
  },
  {
    'codeEtab': 326060003,
    'nomEtab': 'EPP AMBALAHAZO',
    'codeSecteur': 0,
    'zap': 'MAHADITRA',
  },
  {
    'codeEtab': 326060004,
    'nomEtab': 'EPP AMBALAMIRARY',
    'codeSecteur': 0,
    'zap': 'MAHADITRA',
  },
  {
    'codeEtab': 326060005,
    'nomEtab': 'EPP AMBALASOA',
    'codeSecteur': 0,
    'zap': 'MAHADITRA',
  },
  {
    'codeEtab': 326060006,
    'nomEtab': 'EPP AMBATOTERAKA',
    'codeSecteur': 0,
    'zap': 'ANJANOMANANA TSIMIAVAKA',
  },
  {
    'codeEtab': 326060007,
    'nomEtab': 'EPP AMBOHIBORY MORALINA',
    'codeSecteur': 0,
    'zap': 'ANJANOMANANA TSIMIAVAKA',
  },
  {
    'codeEtab': 326060008,
    'nomEtab': 'EPP ANDRAVINDAHY',
    'codeSecteur': 0,
    'zap': 'MAHADITRA',
  },
  {
    'codeEtab': 326060009,
    'nomEtab': 'EPP ANTSAHAMBORONDOLO',
    'codeSecteur': 0,
    'zap': 'MAHADITRA',
  },
  {
    'codeEtab': 326060010,
    'nomEtab': 'EPP ANTSIHARA',
    'codeSecteur': 0,
    'zap': 'ANJANOMANANA TSIMIAVAKA',
  },
  {
    'codeEtab': 326060011,
    'nomEtab': 'EPP MANAMISOA',
    'codeSecteur': 0,
    'zap': 'ANJANOMANANA TSIMIAVAKA',
  },
  {
    'codeEtab': 326060012,
    'nomEtab': 'EPP SABOTSY MAHADITRA',
    'codeSecteur': 0,
    'zap': 'MAHADITRA',
  },
  {
    'codeEtab': 326060013,
    'nomEtab': 'EPP SOATANANA ANDASY',
    'codeSecteur': 0,
    'zap': 'ANJANOMANANA TSIMIAVAKA',
  },
  {
    'codeEtab': 326060014,
    'nomEtab': 'EPP TAMBOHOBE I',
    'codeSecteur': 0,
    'zap': 'MAHADITRA',
  },
  {
    'codeEtab': 326060015,
    'nomEtab': 'EPP TAMBOHOSOA',
    'codeSecteur': 0,
    'zap': 'MAHADITRA',
  },
  {
    'codeEtab': 326060016,
    'nomEtab': 'EPP TSIMAITOHASOA IALATSARA',
    'codeSecteur': 0,
    'zap': 'MAHADITRA',
  },
  {
    'codeEtab': 326060017,
    'nomEtab': 'EPP TSITARY',
    'codeSecteur': 0,
    'zap': 'ANJANOMANANA TSIMIAVAKA',
  },
  {
    'codeEtab': 326060024,
    'nomEtab': 'EPP AMBATOVORY',
    'codeSecteur': 0,
    'zap': 'MAHADITRA',
  },
  {
    'codeEtab': 326060025,
    'nomEtab': 'ECOLE COMMUNAUTAIRE AMBALAMARINA SANDRANATA',
    'codeSecteur': 0,
    'zap': 'MAHADITRA',
  },
  {
    'codeEtab': 326060601,
    'nomEtab': 'ECOLE COMMUNAUTAIRE MAZAVASOA',
    'codeSecteur': 0,
    'zap': 'MAHADITRA',
  },
  {
    'codeEtab': 326070002,
    'nomEtab': 'EPP AMBALAMITSINJONY',
    'codeSecteur': 0,
    'zap': 'MAHASOABE',
  },
  {
    'codeEtab': 326070003,
    'nomEtab': 'EPP AMBALANDAPA',
    'codeSecteur': 0,
    'zap': 'MAHASOABE',
  },
  {
    'codeEtab': 326070004,
    'nomEtab': 'EPP AMBALANDRAMENA',
    'codeSecteur': 0,
    'zap': 'MAHASOABE',
  },
  {
    'codeEtab': 326070005,
    'nomEtab': 'EPP AMBALAVAO MAHAZOARIVO',
    'codeSecteur': 0,
    'zap': 'MAHASOABE',
  },
  {
    'codeEtab': 326070006,
    'nomEtab': 'EPP AMBATOLAHY',
    'codeSecteur': 0,
    'zap': 'MAHASOABE',
  },
  {
    'codeEtab': 326070007,
    'nomEtab': 'EPP AMBATOMIFANONGOA',
    'codeSecteur': 0,
    'zap': 'MAHASOABE',
  },
  {
    'codeEtab': 326070008,
    'nomEtab': 'EPP AMPAMERENANA',
    'codeSecteur': 0,
    'zap': 'MAHASOABE',
  },
  {
    'codeEtab': 326070009,
    'nomEtab': 'EPP MAHASOABE',
    'codeSecteur': 0,
    'zap': 'MAHASOABE',
  },
  {
    'codeEtab': 326070010,
    'nomEtab': 'EPP ANDRANONDAMBO',
    'codeSecteur': 0,
    'zap': 'MAHASOABE',
  },
  {
    'codeEtab': 326070011,
    'nomEtab': 'EPP IAMBARA SOANATAO',
    'codeSecteur': 0,
    'zap': 'MAHASOABE',
  },
  {
    'codeEtab': 326070012,
    'nomEtab': 'EPP MAHASOAKELY',
    'codeSecteur': 0,
    'zap': 'MAHASOABE',
  },
  {
    'codeEtab': 326070013,
    'nomEtab': 'EPP MANAGARIVOTRA',
    'codeSecteur': 0,
    'zap': 'MAHASOABE',
  },
  {
    'codeEtab': 326070014,
    'nomEtab': 'EPP SAHAMALAZA',
    'codeSecteur': 0,
    'zap': 'MAHASOABE',
  },
  {
    'codeEtab': 326070015,
    'nomEtab': 'EPP SOAMANANDRARINY',
    'codeSecteur': 0,
    'zap': 'MAHASOABE',
  },
  {
    'codeEtab': 326070016,
    'nomEtab': 'EPP SOANIERANA MAROVITSIKA',
    'codeSecteur': 0,
    'zap': 'MAHASOABE',
  },
  {
    'codeEtab': 326070017,
    'nomEtab': 'EPP TAMBOHOBE',
    'codeSecteur': 0,
    'zap': 'MAHASOABE',
  },
  {
    'codeEtab': 326070018,
    'nomEtab': 'EPP TANAMBAO MANAMISOA',
    'codeSecteur': 0,
    'zap': 'MAHASOABE',
  },
  {
    'codeEtab': 326070019,
    'nomEtab': 'EPP TSANGAMAHALAZA',
    'codeSecteur': 0,
    'zap': 'MAHASOABE',
  },
  {
    'codeEtab': 326071701,
    'nomEtab': 'ECOLE COMMUNAUTAIRE VOHIMARINA',
    'codeSecteur': 0,
    'zap': 'MAHASOABE',
  },
  {
    'codeEtab': 326080002,
    'nomEtab': 'EPP AMBALAMENA',
    'codeSecteur': 0,
    'zap': 'MANEVA',
  },
  {
    'codeEtab': 326080003,
    'nomEtab': 'EPP AMBALAVATO EST',
    'codeSecteur': 0,
    'zap': 'MANEVA',
  },
  {
    'codeEtab': 326080004,
    'nomEtab': 'EPP AMBALAVAO MANEVA',
    'codeSecteur': 0,
    'zap': 'MANEVA',
  },
  {
    'codeEtab': 326080005,
    'nomEtab': 'EPP AMBALAVOLA',
    'codeSecteur': 0,
    'zap': 'MANEVA',
  },
  {
    'codeEtab': 326080006,
    'nomEtab': 'EPP AMBOHIBORY AVARADRANO',
    'codeSecteur': 0,
    'zap': 'MANEVA',
  },
  {
    'codeEtab': 326080007,
    'nomEtab': 'EPP AMBONDRONA MANEVA',
    'codeSecteur': 0,
    'zap': 'MANEVA',
  },
  {
    'codeEtab': 326080008,
    'nomEtab': 'EPP ANKAZOTANA',
    'codeSecteur': 0,
    'zap': 'MANEVA',
  },
  {
    'codeEtab': 326090001,
    'nomEtab': 'EPP AMBALAMITSINJONY',
    'codeSecteur': 0,
    'zap': 'SOAINDRANA',
  },
  {
    'codeEtab': 326090002,
    'nomEtab': 'EPP ANKERANA OUEST',
    'codeSecteur': 0,
    'zap': 'SOAINDRANA',
  },
  {
    'codeEtab': 326090003,
    'nomEtab': 'EPP SAHAMENA',
    'codeSecteur': 0,
    'zap': 'SOAINDRANA',
  },
  {
    'codeEtab': 326090004,
    'nomEtab': 'EPP SOAINDRANA',
    'codeSecteur': 0,
    'zap': 'SOAINDRANA',
  },
  {
    'codeEtab': 326090101,
    'nomEtab': 'ECOLE COMMUNAUTAIRE AMPAMAREMANA',
    'codeSecteur': 0,
    'zap': 'SOAINDRANA',
  },
  {
    'codeEtab': 326100001,
    'nomEtab': 'EPP AMBALAFANDRAMBATO',
    'codeSecteur': 0,
    'zap': 'TALATA AMPANO',
  },
  {
    'codeEtab': 326100002,
    'nomEtab': 'EPP AMBALATSIMIFARY',
    'codeSecteur': 0,
    'zap': 'TALATA AMPANO',
  },
  {
    'codeEtab': 326100003,
    'nomEtab': 'EPP AMBATOMIHALANA',
    'codeSecteur': 0,
    'zap': 'TALATA AMPANO',
  },
  {
    'codeEtab': 326100004,
    'nomEtab': 'EPP AMPANO TANAMAY',
    'codeSecteur': 0,
    'zap': 'TALATA AMPANO',
  },
  {
    'codeEtab': 326100006,
    'nomEtab': 'EPP ANKAFOTRA',
    'codeSecteur': 0,
    'zap': 'TALATA AMPANO',
  },
  {
    'codeEtab': 326100007,
    'nomEtab': 'EPP ANTAKO TANANDAVA',
    'codeSecteur': 0,
    'zap': 'TALATA AMPANO',
  },
  {
    'codeEtab': 326100008,
    'nomEtab': 'EPP IALADALANGY',
    'codeSecteur': 0,
    'zap': 'TALATA AMPANO',
  },
  {
    'codeEtab': 326100009,
    'nomEtab': 'EPP LANGELA',
    'codeSecteur': 0,
    'zap': 'TALATA AMPANO',
  },
  {
    'codeEtab': 326100010,
    'nomEtab': 'EPP MAHATSANDA',
    'codeSecteur': 0,
    'zap': 'TALATA AMPANO',
  },
  {
    'codeEtab': 326100011,
    'nomEtab': 'EPP MARODINTA',
    'codeSecteur': 0,
    'zap': 'TALATA AMPANO',
  },
  {
    'codeEtab': 326100013,
    'nomEtab': 'EPP MAROVORY',
    'codeSecteur': 0,
    'zap': 'TALATA AMPANO',
  },
  {
    'codeEtab': 326100014,
    'nomEtab': 'EPP TALATA AMPANO',
    'codeSecteur': 0,
    'zap': 'TALATA AMPANO',
  },
  {
    'codeEtab': 326100020,
    'nomEtab': 'EPP VOHIDROA',
    'codeSecteur': 0,
    'zap': 'TALATA AMPANO',
  },
  {
    'codeEtab': 326110002,
    'nomEtab': 'EPP ANDRANOBE',
    'codeSecteur': 0,
    'zap': 'VINANITELO',
  },
  {
    'codeEtab': 326110003,
    'nomEtab': 'EPP AMBALAMANENJANA',
    'codeSecteur': 0,
    'zap': 'VINANITELO',
  },
  {
    'codeEtab': 326110004,
    'nomEtab': 'EPP AMBALAVAO SAHAFA',
    'codeSecteur': 0,
    'zap': 'VINANITELO',
  },
  {
    'codeEtab': 326110005,
    'nomEtab': 'EPP AMBOHINAMBOARINA',
    'codeSecteur': 0,
    'zap': 'VINANITELO',
  },
  {
    'codeEtab': 326110006,
    'nomEtab': 'EPP ANARA',
    'codeSecteur': 0,
    'zap': 'VINANITELO',
  },
  {
    'codeEtab': 326110007,
    'nomEtab': 'EPP ANDASINDRAIVONY',
    'codeSecteur': 0,
    'zap': 'VINANITELO',
  },
  {
    'codeEtab': 326110008,
    'nomEtab': 'EPP ANDOHARANO',
    'codeSecteur': 0,
    'zap': 'VINANITELO',
  },
  {
    'codeEtab': 326110009,
    'nomEtab': 'EPP ANDRAIDODO',
    'codeSecteur': 0,
    'zap': 'VINANITELO',
  },
  {
    'codeEtab': 326110010,
    'nomEtab': 'EPP NANDRAINA',
    'codeSecteur': 0,
    'zap': 'VINANITELO',
  },
  {
    'codeEtab': 326110011,
    'nomEtab': 'EPP SAHARAIVO',
    'codeSecteur': 0,
    'zap': 'VINANITELO',
  },
  {
    'codeEtab': 326110012,
    'nomEtab': 'EPP SANDRANATA',
    'codeSecteur': 0,
    'zap': 'VINANITELO',
  },
  {
    'codeEtab': 326110013,
    'nomEtab': 'EPP TANAMBAO',
    'codeSecteur': 0,
    'zap': 'VINANITELO',
  },
  {
    'codeEtab': 326110014,
    'nomEtab': 'EPP TSARAMANDROSO',
    'codeSecteur': 0,
    'zap': 'VINANITELO',
  },
  {
    'codeEtab': 326110016,
    'nomEtab': 'EPP MANAOTSARA',
    'codeSecteur': 0,
    'zap': 'VINANITELO',
  },
  {
    'codeEtab': 326110018,
    'nomEtab': 'EPP MANIRISOA',
    'codeSecteur': 0,
    'zap': 'VINANITELO',
  },
  {
    'codeEtab': 326110023,
    'nomEtab': 'EPP MANANTENASOA I',
    'codeSecteur': 0,
    'zap': 'VINANITELO',
  },
  {
    'codeEtab': 326110025,
    'nomEtab': 'EPP SOANIARENANA I',
    'codeSecteur': 0,
    'zap': 'VINANITELO',
  },
  {
    'codeEtab': 326110026,
    'nomEtab': 'ECOLE COMMUNAUTAIRE AMBOHIMALAZA',
    'codeSecteur': 0,
    'zap': 'VINANITELO',
  },
  {
    'codeEtab': 326110027,
    'nomEtab': 'ECOLE COMMUNAUTAIRE NAMARINA',
    'codeSecteur': 0,
    'zap': 'VINANITELO',
  },
  {
    'codeEtab': 326110028,
    'nomEtab': 'ECOLE COMMUNAUTAIRE SOANIERENANA II',
    'codeSecteur': 0,
    'zap': 'VINANITELO',
  },
  {
    'codeEtab': 326110031,
    'nomEtab': 'EPP MANANTENASOA II',
    'codeSecteur': 0,
    'zap': 'VINANITELO',
  },
  {
    'codeEtab': 326110032,
    'nomEtab': 'ECOLE COMMUNAUTAIRE ANKAE',
    'codeSecteur': 0,
    'zap': 'VINANITELO',
  },
  {
    'codeEtab': 326110034,
    'nomEtab': 'ECOLE COMMUNAUTAIRE LOVASOA',
    'codeSecteur': 0,
    'zap': 'VINANITELO',
  },
  {
    'codeEtab': 326110036,
    'nomEtab': 'ECOLE COMMUNAUTAIRE FANILO ANOSIVORY',
    'codeSecteur': 0,
    'zap': 'VINANITELO',
  },
  {
    'codeEtab': 326110037,
    'nomEtab': 'ECOLE COMMUNAUTAIRE ANDRANOHERANA',
    'codeSecteur': 0,
    'zap': 'VINANITELO',
  },
  {
    'codeEtab': 326120003,
    'nomEtab': 'EPP AMBALAKINANA',
    'codeSecteur': 0,
    'zap': 'VOHIBATO OUEST',
  },
  {
    'codeEtab': 326120004,
    'nomEtab': 'EPP AMBALATANIFOTSY',
    'codeSecteur': 0,
    'zap': 'VOHIBATO OUEST',
  },
  {
    'codeEtab': 326120005,
    'nomEtab': 'EPP AMBY',
    'codeSecteur': 0,
    'zap': 'VOHIBATO OUEST',
  },
  {
    'codeEtab': 326120006,
    'nomEtab': 'EPP ANDOHAMANDRANOMAVO',
    'codeSecteur': 0,
    'zap': 'VOHIBATO OUEST',
  },
  {
    'codeEtab': 326120007,
    'nomEtab': 'EPP ANTSIOBE',
    'codeSecteur': 0,
    'zap': 'VOHIBATO OUEST',
  },
  {
    'codeEtab': 326120008,
    'nomEtab': 'EPP TAMBOHOBE',
    'codeSecteur': 0,
    'zap': 'VOHIBATO OUEST',
  },
  {
    'codeEtab': 326120010,
    'nomEtab': 'EPP TSIANESENA',
    'codeSecteur': 0,
    'zap': 'VOHIBATO OUEST',
  },
  {
    'codeEtab': 326130002,
    'nomEtab': 'EPP AMBAIBO',
    'codeSecteur': 0,
    'zap': 'LAMOSINA',
  },
  {
    'codeEtab': 326130003,
    'nomEtab': 'EPP AMBALAMANANDRAY',
    'codeSecteur': 0,
    'zap': 'VOHIMARINA',
  },
  {
    'codeEtab': 326130004,
    'nomEtab': 'EPP AMBALATSIAFAKOMBY',
    'codeSecteur': 0,
    'zap': 'VOHIMARINA',
  },
  {
    'codeEtab': 326130005,
    'nomEtab': 'EPP AMBALAVAO LAZAINARIVO',
    'codeSecteur': 0,
    'zap': 'VOHIMARINA',
  },
  {
    'codeEtab': 326130006,
    'nomEtab': 'EPP AMBATOHARANANA',
    'codeSecteur': 0,
    'zap': 'LAMOSINA',
  },
  {
    'codeEtab': 326130007,
    'nomEtab': 'EPP AMBOAVONANA',
    'codeSecteur': 0,
    'zap': 'LAMOSINA',
  },
  {
    'codeEtab': 326130008,
    'nomEtab': 'EPP ANAKASANA VAOLAHY',
    'codeSecteur': 0,
    'zap': 'LAMOSINA',
  },
  {
    'codeEtab': 326130009,
    'nomEtab': 'EPP ANJA LAMOSINA',
    'codeSecteur': 0,
    'zap': 'LAMOSINA',
  },
  {
    'codeEtab': 326130010,
    'nomEtab': 'EPP ANJANOMALAZA',
    'codeSecteur': 0,
    'zap': 'VOHIMARINA',
  },
  {
    'codeEtab': 326130011,
    'nomEtab': 'EPP ANOTSIMAINTY',
    'codeSecteur': 0,
    'zap': 'LAMOSINA',
  },
  {
    'codeEtab': 326130012,
    'nomEtab': 'EPP BESOA',
    'codeSecteur': 0,
    'zap': 'VOHIMARINA',
  },
  {
    'codeEtab': 326130013,
    'nomEtab': 'EPP ITSIFO',
    'codeSecteur': 0,
    'zap': 'VOHIMARINA',
  },
  {
    'codeEtab': 326130014,
    'nomEtab': 'EPP IVORY TSIFO',
    'codeSecteur': 0,
    'zap': 'VOHIMARINA',
  },
  {
    'codeEtab': 326130015,
    'nomEtab': 'EPP LAMOSINA',
    'codeSecteur': 0,
    'zap': 'LAMOSINA',
  },
  {
    'codeEtab': 326130016,
    'nomEtab': 'EPP MAHAFALY',
    'codeSecteur': 0,
    'zap': 'VOHIMARINA',
  },
  {
    'codeEtab': 326130017,
    'nomEtab': 'EPP MIARAMANDROSO',
    'codeSecteur': 0,
    'zap': 'VOHIMARINA',
  },
  {
    'codeEtab': 326130018,
    'nomEtab': 'EPP SOARANO ANJA',
    'codeSecteur': 0,
    'zap': 'LAMOSINA',
  },
  {
    'codeEtab': 326130019,
    'nomEtab': 'EPP TAMBOHOANIVO',
    'codeSecteur': 0,
    'zap': 'VOHIMARINA',
  },
  {
    'codeEtab': 326130020,
    'nomEtab': 'EPP VOATAVOLEMAKA',
    'codeSecteur': 0,
    'zap': 'LAMOSINA',
  },
  {
    'codeEtab': 326130021,
    'nomEtab': 'EPP VOHIMARINA',
    'codeSecteur': 0,
    'zap': 'VOHIMARINA',
  },
  {
    'codeEtab': 326130022,
    'nomEtab': 'EPP ANDRANONDRAIKITRA',
    'codeSecteur': 0,
    'zap': 'VOHIMARINA',
  },
  {
    'codeEtab': 326130023,
    'nomEtab': 'EPP TANAMBAO',
    'codeSecteur': 0,
    'zap': 'VOHIMARINA',
  },
  {
    'codeEtab': 326130024,
    'nomEtab': 'ECOLE COMMUNAUTAIRE BESOARAVY',
    'codeSecteur': 0,
    'zap': 'LAMOSINA',
  },
  {
    'codeEtab': 326130025,
    'nomEtab': 'EPP FOPOHONY',
    'codeSecteur': 0,
    'zap': 'LAMOSINA',
  },
  {
    'codeEtab': 326130026,
    'nomEtab': 'EPP SOMONDRANO',
    'codeSecteur': 0,
    'zap': 'LAMOSINA',
  },
  {
    'codeEtab': 326130027,
    'nomEtab': 'EPP MANAITSA',
    'codeSecteur': 0,
    'zap': 'LAMOSINA',
  },
  {
    'codeEtab': 326130028,
    'nomEtab': 'EPP TSARATANANA',
    'codeSecteur': 0,
    'zap': 'VOHIMARINA',
  },
  {
    'codeEtab': 326130029,
    'nomEtab': 'ECOLE COMMUNAUTAIRE IKINA',
    'codeSecteur': 0,
    'zap': 'VOHIMARINA',
  },
  {
    'codeEtab': 326130032,
    'nomEtab': 'ECOLE COMMUNAUTAIRE SAKAMANANA',
    'codeSecteur': 0,
    'zap': 'VOHIMARINA',
  },
  {
    'codeEtab': 326130033,
    'nomEtab': 'ECOLE COMMUNAUTAIRE VOENANA',
    'codeSecteur': 0,
    'zap': 'VOHIMARINA',
  },
  {
    'codeEtab': 326140002,
    'nomEtab': 'EPP AMBALAHAMBANA',
    'codeSecteur': 0,
    'zap': 'VOHITRAFENO',
  },
  {
    'codeEtab': 326140003,
    'nomEtab': 'EPP AMBALAMISAOTRA',
    'codeSecteur': 0,
    'zap': 'VOHITRAFENO',
  },
  {
    'codeEtab': 326140004,
    'nomEtab': 'EPP AMBALAVAO',
    'codeSecteur': 0,
    'zap': 'VOHITRAFENO',
  },
  {
    'codeEtab': 326140005,
    'nomEtab': 'EPP AMBOHIMALAZA',
    'codeSecteur': 0,
    'zap': 'VOHITRAFENO',
  },
  {
    'codeEtab': 326140006,
    'nomEtab': 'EPP AMBOHINAMBOARINA',
    'codeSecteur': 0,
    'zap': 'VOHITRAFENO',
  },
  {
    'codeEtab': 326140007,
    'nomEtab': 'EPP ANDOMOTRA',
    'codeSecteur': 0,
    'zap': 'VOHITRAFENO',
  },
  {
    'codeEtab': 326140008,
    'nomEtab': 'EPP ANJOZOROKELY',
    'codeSecteur': 0,
    'zap': 'VOHITRAFENO',
  },
  {
    'codeEtab': 326140009,
    'nomEtab': 'EPP IALAMARINA',
    'codeSecteur': 0,
    'zap': 'VOHITRAFENO',
  },
  {
    'codeEtab': 326140010,
    'nomEtab': 'EPP MAROTAVY AMBOHIPIAFANANA',
    'codeSecteur': 0,
    'zap': 'VOHITRAFENO',
  },
  {
    'codeEtab': 326140011,
    'nomEtab': 'EPP SAMBOHOVA',
    'codeSecteur': 0,
    'zap': 'VOHITRAFENO',
  },
  {
    'codeEtab': 326140015,
    'nomEtab': 'EPP VOHITSOA',
    'codeSecteur': 0,
    'zap': 'VOHITRAFENO',
  },
  {
    'codeEtab': 326150201,
    'nomEtab': 'ECOLE COMMUNAUTAIRE AMBALAMARINA',
    'codeSecteur': 0,
    'zap': 'ANJANOMANANA TSIMIAVAKA',
  },
  {
    'codeEtab': 326160001,
    'nomEtab': 'ECOLE COMMUNAUTAIRE AMPEMBY',
    'codeSecteur': 0,
    'zap': 'LAMOSINA',
  },
  {
    'codeEtab': 326010001,
    'nomEtab': 'CEG LOVASOA ALAKAMISY ITENINA',
    'codeSecteur': 0,
    'zap': 'ALAKAMISY ITENINA',
  },
  {
    'codeEtab': 326010018,
    'nomEtab': 'CEG ANJANAMAHASOA EST',
    'codeSecteur': 0,
    'zap': 'ALAKAMISY ITENINA',
  },
  {
    'codeEtab': 326010019,
    'nomEtab': 'CEG SANGASANGA CENTRE',
    'codeSecteur': 0,
    'zap': 'ALAKAMISY ITENINA',
  },
  {
    'codeEtab': 326010020,
    'nomEtab': 'CEG TANDROKAZO',
    'codeSecteur': 0,
    'zap': 'ALAKAMISY ITENINA',
  },
  {
    'codeEtab': 326020001,
    'nomEtab': 'CEG ANDRANOMIDITRA',
    'codeSecteur': 0,
    'zap': 'ANDRANOMIDITRA',
  },
  {
    'codeEtab': 326020017,
    'nomEtab': 'CEG COMMUNAUTAIRE MAROMPANIRY',
    'codeSecteur': 0,
    'zap': 'ANDRANOMIDITRA',
  },
  {
    'codeEtab': 326020018,
    'nomEtab': 'CEG AMBONDRONA',
    'codeSecteur': 0,
    'zap': 'ANDRANOMIDITRA',
  },
  {
    'codeEtab': 326020024,
    'nomEtab': 'CEG FANIRIANA',
    'codeSecteur': 0,
    'zap': 'ANDRANOMIDITRA',
  },
  {
    'codeEtab': 326030001,
    'nomEtab': 'CEG ANDRANOVORIVATO',
    'codeSecteur': 0,
    'zap': 'ANDRANOVORIVATO',
  },
  {
    'codeEtab': 326030022,
    'nomEtab': 'CEG IHAVELOMANA',
    'codeSecteur': 0,
    'zap': 'ANDRANOVORIVATO',
  },
  {
    'codeEtab': 326030023,
    'nomEtab': 'CEG TSINJONIHOAVY',
    'codeSecteur': 0,
    'zap': 'ANDRANOVORIVATO',
  },
  {
    'codeEtab': 326030024,
    'nomEtab': 'CEG AMBATOBEVENTY',
    'codeSecteur': 0,
    'zap': 'ANDRANOVORIVATO',
  },
  {
    'codeEtab': 326030025,
    'nomEtab': 'CEG AMBATOSOAMIRAY',
    'codeSecteur': 0,
    'zap': 'ANDRANOVORIVATO',
  },
  {
    'codeEtab': 326040006,
    'nomEtab': 'CEG ANKAROMALAZA MIFANASOA',
    'codeSecteur': 0,
    'zap': 'ANKAROMALAZA MIFANASOA',
  },
  {
    'codeEtab': 326050001,
    'nomEtab': 'CEG IHAZOARA',
    'codeSecteur': 0,
    'zap': 'IHAZOARA',
  },
  {
    'codeEtab': 326050015,
    'nomEtab': 'CEG ANDRARAMILA',
    'codeSecteur': 0,
    'zap': 'IHAZOARA',
  },
  {
    'codeEtab': 326060001,
    'nomEtab': 'CEG MAHADITRA',
    'codeSecteur': 0,
    'zap': 'MAHADITRA',
  },
  {
    'codeEtab': 326060020,
    'nomEtab': 'CEG ANJANOMANANA',
    'codeSecteur': 0,
    'zap': 'ANJANOMANANA TSIMIAVAKA',
  },
  {
    'codeEtab': 326060021,
    'nomEtab': 'CEG VATOMITANTANA',
    'codeSecteur': 0,
    'zap': 'ANJANOMANANA TSIMIAVAKA',
  },
  {
    'codeEtab': 326060022,
    'nomEtab': 'CEG TSIMAITOHASOA',
    'codeSecteur': 0,
    'zap': 'MAHADITRA',
  },
  {
    'codeEtab': 326060023,
    'nomEtab': 'CEG VOHITRAVEOTRA',
    'codeSecteur': 0,
    'zap': 'MAHADITRA',
  },
  {
    'codeEtab': 326060701,
    'nomEtab': 'CEG COMMUNAUTAIRE IALATSARA',
    'codeSecteur': 0,
    'zap': 'MAHADITRA',
  },
  {
    'codeEtab': 326070001,
    'nomEtab': 'CEG MAHASOABE TSARAFARA',
    'codeSecteur': 0,
    'zap': 'MAHASOABE',
  },
  {
    'codeEtab': 326070021,
    'nomEtab': 'CEG ANJANAMAHASOA',
    'codeSecteur': 0,
    'zap': 'MAHASOABE',
  },
  {
    'codeEtab': 326070022,
    'nomEtab': 'CEG AMBALAMITSINJONY',
    'codeSecteur': 0,
    'zap': 'MAHASOABE',
  },
  {
    'codeEtab': 326070025,
    'nomEtab': 'CEG AMBATOLAHY',
    'codeSecteur': 0,
    'zap': 'MAHASOABE',
  },
  {
    'codeEtab': 326070026,
    'nomEtab': 'CEG COMMUNAUTAIRE TAMBOHOBE',
    'codeSecteur': 0,
    'zap': 'MAHASOABE',
  },
  {
    'codeEtab': 326070027,
    'nomEtab': 'CEG COMMUNAUTAIRE AMBOASARIMAY',
    'codeSecteur': 0,
    'zap': 'MAHASOABE',
  },
  {
    'codeEtab': 326080001,
    'nomEtab': 'CEG MANEVA',
    'codeSecteur': 0,
    'zap': 'MANEVA',
  },
  {
    'codeEtab': 326090005,
    'nomEtab': 'CEG SOAINDRANA',
    'codeSecteur': 0,
    'zap': 'SOAINDRANA',
  },
  {
    'codeEtab': 326100016,
    'nomEtab': 'CEG TALATA AMPANO',
    'codeSecteur': 0,
    'zap': 'TALATA AMPANO',
  },
  {
    'codeEtab': 326100019,
    'nomEtab': 'CEG IHARANANY',
    'codeSecteur': 0,
    'zap': 'TALATA AMPANO',
  },
  {
    'codeEtab': 326100101,
    'nomEtab': 'CEG COMMUNAUTAIRE AMBALAFANDRAMBATO',
    'codeSecteur': 0,
    'zap': 'TALATA AMPANO',
  },
  {
    'codeEtab': 326110001,
    'nomEtab': 'CEG VINANITELO',
    'codeSecteur': 0,
    'zap': 'VINANITELO',
  },
  {
    'codeEtab': 326110029,
    'nomEtab': 'CEG COMMUNAUTAIRE ANDASINDRAIVONY',
    'codeSecteur': 0,
    'zap': 'VINANITELO',
  },
  {
    'codeEtab': 326110030,
    'nomEtab': 'CEG COMMUNAUTAIRE ANDRAIDODO',
    'codeSecteur': 0,
    'zap': 'VINANITELO',
  },
  {
    'codeEtab': 326110401,
    'nomEtab': 'CEG COMMUNAUTAIRE FIVOARANA ANDOHAMATSIATRA',
    'codeSecteur': 0,
    'zap': 'VINANITELO',
  },
  {
    'codeEtab': 326120009,
    'nomEtab': 'CEG VOHIBATO OUEST',
    'codeSecteur': 0,
    'zap': 'VOHIBATO OUEST',
  },
  {
    'codeEtab': 326130001,
    'nomEtab': 'CEG VOHIMARINA',
    'codeSecteur': 0,
    'zap': 'VOHIMARINA',
  },
  {
    'codeEtab': 326130030,
    'nomEtab': 'CEG COMMUNAUTAIRE MAROMANA',
    'codeSecteur': 0,
    'zap': 'LAMOSINA',
  },
  {
    'codeEtab': 326130031,
    'nomEtab': 'CEG COMMUNAUTAIRE VAHAMBE',
    'codeSecteur': 0,
    'zap': 'VOHIMARINA',
  },
  {
    'codeEtab': 326140001,
    'nomEtab': 'CEG VOHITRAFENO',
    'codeSecteur': 0,
    'zap': 'VOHITRAFENO',
  },
  {
    'codeEtab': 326140013,
    'nomEtab': 'CEG MITOKO EST',
    'codeSecteur': 0,
    'zap': 'VOHITRAFENO',
  },
  {
    'codeEtab': 326140014,
    'nomEtab': 'CEG COMMUNAUTAIRE AMBOHIMANA',
    'codeSecteur': 0,
    'zap': 'VOHITRAFENO',
  },
  {
    'codeEtab': 326140017,
    'nomEtab': 'CEG COMMUNAUTAIRE MAROTAVY',
    'codeSecteur': 0,
    'zap': 'VOHITRAFENO',
  },
  {
    'codeEtab': 326010017,
    'nomEtab': 'LYCEE ALAKAMISY ITENINA',
    'codeSecteur': 0,
    'zap': 'ALAKAMISY ITENINA',
  },
  {
    'codeEtab': 326020022,
    'nomEtab': 'LYCEE ANDRANOMIDITRA',
    'codeSecteur': 0,
    'zap': 'ANDRANOMIDITRA',
  },
  {
    'codeEtab': 326030027,
    'nomEtab': 'LYCEE ANDRANOVORIVATO',
    'codeSecteur': 0,
    'zap': 'ANDRANOVORIVATO',
  },
  {
    'codeEtab': 326040201,
    'nomEtab': 'LYCEE COMMUNAUTAIRE ANKAROMALAZA MIFANASOA',
    'codeSecteur': 0,
    'zap': 'ANKAROMALAZA MIFANASOA',
  },
  {
    'codeEtab': 326060018,
    'nomEtab': 'LYCEE MAHADITRA',
    'codeSecteur': 0,
    'zap': 'MAHADITRA',
  },
  {
    'codeEtab': 326070020,
    'nomEtab': 'LYCEE MAHASOABE',
    'codeSecteur': 0,
    'zap': 'MAHASOABE',
  },
  {
    'codeEtab': 326080201,
    'nomEtab': 'LYCEE COMMUNAUTAIRE MANEVA',
    'codeSecteur': 0,
    'zap': 'MANEVA',
  },
  {
    'codeEtab': 326090201,
    'nomEtab': 'LYCEE COMMUNAUTAIRE SOAINDRANA',
    'codeSecteur': 0,
    'zap': 'SOAINDRANA',
  },
  {
    'codeEtab': 326100018,
    'nomEtab': 'LYCEE TALATA AMPANO',
    'codeSecteur': 0,
    'zap': 'TALATA AMPANO',
  },
  {
    'codeEtab': 326110024,
    'nomEtab': 'LYCEE VINANITELO',
    'codeSecteur': 0,
    'zap': 'VINANITELO',
  },
  {
    'codeEtab': 326130034,
    'nomEtab': 'LYCEE VOHIMARINA',
    'codeSecteur': 0,
    'zap': 'VOHIMARINA',
  },
  {
    'codeEtab': 326140016,
    'nomEtab': 'LYCEE VOHITRAFENO',
    'codeSecteur': 0,
    'zap': 'VOHITRAFENO',
  },
  {
    'codeEtab': 326150001,
    'nomEtab': 'LYCEE ANJANOMANANA',
    'codeSecteur': 0,
    'zap': 'ANJANOMANANA TSIMIAVAKA',
  },
  {
    'codeEtab': 326011001,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE AMBALAMARINA EST',
    'codeSecteur': 1,
    'zap': 'ALAKAMISY ITENINA',
  },
  {
    'codeEtab': 326011002,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE SAINT JEAN BOSCO',
    'codeSecteur': 1,
    'zap': 'ALAKAMISY ITENINA',
  },
  {
    'codeEtab': 326011008,
    'nomEtab': 'COLLEGE PRIVE FJKM TSARAFARA',
    'codeSecteur': 1,
    'zap': 'ALAKAMISY ITENINA',
  },
  {
    'codeEtab': 326011011,
    'nomEtab': 'LYCEE PRIVE AVAL',
    'codeSecteur': 1,
    'zap': 'ALAKAMISY ITENINA',
  },
  {
    'codeEtab': 326020027,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE ANTARAMBIBY',
    'codeSecteur': 1,
    'zap': 'ANDRANOMIDITRA',
  },
  {
    'codeEtab': 326021001,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE AMPANOSARA',
    'codeSecteur': 1,
    'zap': 'ANDRANOMIDITRA',
  },
  {
    'codeEtab': 326021004,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE FANILO MANAOVASOA',
    'codeSecteur': 1,
    'zap': 'ANDRANOMIDITRA',
  },
  {
    'codeEtab': 326021005,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE SAINT BENOIT AMPIANA',
    'codeSecteur': 1,
    'zap': 'ANDRANOMIDITRA',
  },
  {
    'codeEtab': 326021006,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE TANITSIHOMEHY A',
    'codeSecteur': 1,
    'zap': 'ANDRANOMIDITRA',
  },
  {
    'codeEtab': 326021007,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE TANJOMBE',
    'codeSecteur': 1,
    'zap': 'ANDRANOMIDITRA',
  },
  {
    'codeEtab': 326021008,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE TSARAMANDROSO',
    'codeSecteur': 1,
    'zap': 'ANDRANOMIDITRA',
  },
  {
    'codeEtab': 326021010,
    'nomEtab': 'ECOLE PRIVEE LUTHERIENNE SOANIERANA TETEZANTANY',
    'codeSecteur': 1,
    'zap': 'ANDRANOMIDITRA',
  },
  {
    'codeEtab': 326021011,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE RANOMENA',
    'codeSecteur': 1,
    'zap': 'ANDRANOMIDITRA',
  },
  {
    'codeEtab': 326021013,
    'nomEtab':
        'ECOLE PRIVEE CATHOLIQUE SAINTE THERESE DE L\'ENFANT JESUS MANEVA',
    'codeSecteur': 1,
    'zap': 'ANDRANOMIDITRA',
  },
  {
    'codeEtab': 326021018,
    'nomEtab': 'COLLEGE PRIVE MANAOSOA MAROHADY',
    'codeSecteur': 1,
    'zap': 'ANDRANOMIDITRA',
  },
  {
    'codeEtab': 326021019,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE ANDRANOMBAO',
    'codeSecteur': 1,
    'zap': 'ANDRANOMIDITRA',
  },
  {
    'codeEtab': 326031001,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE AMBALAMAHATSINJO',
    'codeSecteur': 1,
    'zap': 'ANDRANOVORIVATO',
  },
  {
    'codeEtab': 326031003,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE AMBALAVAO TATAO',
    'codeSecteur': 1,
    'zap': 'ANDRANOVORIVATO',
  },
  {
    'codeEtab': 326031004,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE AMBATOVORY',
    'codeSecteur': 1,
    'zap': 'ANDRANOVORIVATO',
  },
  {
    'codeEtab': 326031005,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE ANKARITSIANANANA',
    'codeSecteur': 1,
    'zap': 'ANDRANOVORIVATO',
  },
  {
    'codeEtab': 326031006,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE ANKERANA SOMAINA',
    'codeSecteur': 1,
    'zap': 'ANDRANOVORIVATO',
  },
  {
    'codeEtab': 326031008,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE IKOLO',
    'codeSecteur': 1,
    'zap': 'ANDRANOVORIVATO',
  },
  {
    'codeEtab': 326031009,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE SAINT MICHEL',
    'codeSecteur': 1,
    'zap': 'ANDRANOVORIVATO',
  },
  {
    'codeEtab': 326031010,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE SAINT PAUL IKALAVAO',
    'codeSecteur': 1,
    'zap': 'ANDRANOVORIVATO',
  },
  {
    'codeEtab': 326031011,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE SAINTSOA',
    'codeSecteur': 1,
    'zap': 'ANDRANOVORIVATO',
  },
  {
    'codeEtab': 326031012,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE SAINT JOSEPH SIRAO',
    'codeSecteur': 1,
    'zap': 'ANDRANOVORIVATO',
  },
  {
    'codeEtab': 326031013,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE SAINT FAMILLE TAMBOHOANIVO',
    'codeSecteur': 1,
    'zap': 'ANDRANOVORIVATO',
  },
  {
    'codeEtab': 326031016,
    'nomEtab': 'ECOLE PRIVEE FJKM ANDROMIVATO',
    'codeSecteur': 1,
    'zap': 'ANDRANOVORIVATO',
  },
  {
    'codeEtab': 326031019,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE SAINTE JEANNE D\'ARC VOHIHAMBANA',
    'codeSecteur': 1,
    'zap': 'ANDRANOVORIVATO',
  },
  {
    'codeEtab': 326031020,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE AMBALATSILA',
    'codeSecteur': 1,
    'zap': 'ANDRANOVORIVATO',
  },
  {
    'codeEtab': 326031021,
    'nomEtab': 'ECOLE NON CONFESSIONNELLE RATOMANAGNARIVO',
    'codeSecteur': 1,
    'zap': 'ANDRANOVORIVATO',
  },
  {
    'codeEtab': 326031022,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE TANAMBAO SAHAVANANA',
    'codeSecteur': 1,
    'zap': 'ANDRANOVORIVATO',
  },
  {
    'codeEtab': 326031025,
    'nomEtab': 'COLLEGE PRIVE MANOVOSOA ANDRANOVORIVATO',
    'codeSecteur': 1,
    'zap': 'ANDRANOVORIVATO',
  },
  {
    'codeEtab': 326031026,
    'nomEtab': 'ECOLE PRIVEE FANEVA',
    'codeSecteur': 1,
    'zap': 'ANDRANOVORIVATO',
  },
  {
    'codeEtab': 326041001,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE ZARABE FANAMEANA',
    'codeSecteur': 1,
    'zap': 'ANKAROMALAZA MIFANASOA',
  },
  {
    'codeEtab': 326041003,
    'nomEtab': 'COLLEGE PRIVE MANDROSO',
    'codeSecteur': 1,
    'zap': 'ANKAROMALAZA MIFANASOA',
  },
  {
    'codeEtab': 326041004,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE ASANA VATOMITANTANA',
    'codeSecteur': 1,
    'zap': 'ANKAROMALAZA MIFANASOA',
  },
  {
    'codeEtab': 326050501,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE AMBATOBE',
    'codeSecteur': 1,
    'zap': 'IHAZOARA',
  },
  {
    'codeEtab': 326051002,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE AMBOHIMARANITRA',
    'codeSecteur': 1,
    'zap': 'IHAZOARA',
  },
  {
    'codeEtab': 326051007,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE AMBOLO',
    'codeSecteur': 1,
    'zap': 'IHAZOARA',
  },
  {
    'codeEtab': 326061001,
    'nomEtab': 'COLLEGE PRIVE FJKM AMBALAMANENJANA I',
    'codeSecteur': 1,
    'zap': 'MAHADITRA',
  },
  {
    'codeEtab': 326061002,
    'nomEtab': 'COLLEGE VICTOIRE RASOAMANARIVO MORALINA',
    'codeSecteur': 1,
    'zap': 'MAHADITRA',
  },
  {
    'codeEtab': 326061004,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE AMBALAMANENJANA II',
    'codeSecteur': 1,
    'zap': 'MAHADITRA',
  },
  {
    'codeEtab': 326061006,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE ANTSAHAMBORONDOLO',
    'codeSecteur': 1,
    'zap': 'MAHADITRA',
  },
  {
    'codeEtab': 326061007,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE MAROFOTOTRA',
    'codeSecteur': 1,
    'zap': 'MAHADITRA',
  },
  {
    'codeEtab': 326061009,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE SOATANANA',
    'codeSecteur': 1,
    'zap': 'ANJANOMANANA TSIMIAVAKA',
  },
  {
    'codeEtab': 326061011,
    'nomEtab': 'ECOLE CATHOLIQUE ANKISIRA',
    'codeSecteur': 1,
    'zap': 'MAHADITRA',
  },
  {
    'codeEtab': 326071001,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE AMBOASARIMAY',
    'codeSecteur': 1,
    'zap': 'MAHASOABE',
  },
  {
    'codeEtab': 326071002,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE DE NOSIVATO',
    'codeSecteur': 1,
    'zap': 'MAHASOABE',
  },
  {
    'codeEtab': 326071003,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE DE TAMBOHOBE',
    'codeSecteur': 1,
    'zap': 'MAHASOABE',
  },
  {
    'codeEtab': 326071004,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE DE TSANGAMAHALAZA',
    'codeSecteur': 1,
    'zap': 'MAHASOABE',
  },
  {
    'codeEtab': 326071005,
    'nomEtab': 'LYCEE CATHOLIQUE SAINT LOUIS DE GONZAGUE',
    'codeSecteur': 1,
    'zap': 'MAHASOABE',
  },
  {
    'codeEtab': 326071006,
    'nomEtab': 'COLLEGE SEDERA FAHAZAVANA MAHASOABE',
    'codeSecteur': 1,
    'zap': 'MAHASOABE',
  },
  {
    'codeEtab': 326071010,
    'nomEtab': 'ECOLE NON CONFESSIONNELLE AKANY MIZARASOA',
    'codeSecteur': 1,
    'zap': 'MAHASOABE',
  },
  {
    'codeEtab': 326071011,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE DE VOHIMARINA',
    'codeSecteur': 1,
    'zap': 'MAHASOABE',
  },
  {
    'codeEtab': 326071012,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE AMBALAVAO LALANGINA',
    'codeSecteur': 1,
    'zap': 'MAHASOABE',
  },
  {
    'codeEtab': 326071014,
    'nomEtab': 'LYCEE PRIVE SUN RISE SCHOOL MAHASOABE',
    'codeSecteur': 1,
    'zap': 'MAHASOABE',
  },
  {
    'codeEtab': 326071020,
    'nomEtab': 'LYCEE PRIVE LA MERVEILLE MAHASOABE',
    'codeSecteur': 1,
    'zap': 'MAHASOABE',
  },
  {
    'codeEtab': 326071023,
    'nomEtab': 'LYCEE PRIVE MANOVOSOA',
    'codeSecteur': 1,
    'zap': 'MAHASOABE',
  },
  {
    'codeEtab': 326080601,
    'nomEtab': 'ECOLE PRIVEE LUTHERIENNE NAMANA ANKERANA',
    'codeSecteur': 1,
    'zap': 'MANEVA',
  },
  {
    'codeEtab': 326081001,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE AMBALAVAO ANKAZOTANA',
    'codeSecteur': 1,
    'zap': 'MANEVA',
  },
  {
    'codeEtab': 326081002,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE AMPASIMBE',
    'codeSecteur': 1,
    'zap': 'MANEVA',
  },
  {
    'codeEtab': 326081004,
    'nomEtab': 'ECOLE PRIVEE LA RACINE',
    'codeSecteur': 1,
    'zap': 'MANEVA',
  },
  {
    'codeEtab': 326091002,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE FO MASIN\'I JESOA',
    'codeSecteur': 1,
    'zap': 'SOAINDRANA',
  },
  {
    'codeEtab': 326091003,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE SAINT DONATIEN AMBONDRONA',
    'codeSecteur': 1,
    'zap': 'SOAINDRANA',
  },
  {
    'codeEtab': 326091004,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE AMPAMAREMANA',
    'codeSecteur': 1,
    'zap': 'SOAINDRANA',
  },
  {
    'codeEtab': 326101002,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE IJERY',
    'codeSecteur': 1,
    'zap': 'TALATA AMPANO',
  },
  {
    'codeEtab': 326101004,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE SOAVADIA MAROVOVOTANY',
    'codeSecteur': 1,
    'zap': 'TALATA AMPANO',
  },
  {
    'codeEtab': 326101005,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE SAINT JOSEPH AMPANO',
    'codeSecteur': 1,
    'zap': 'TALATA AMPANO',
  },
  {
    'codeEtab': 326101007,
    'nomEtab': 'COLLEGE PRIVE CATHOLIQUE SAINT STANISLAS KOSTKA',
    'codeSecteur': 1,
    'zap': 'TALATA AMPANO',
  },
  {
    'codeEtab': 326101012,
    'nomEtab': 'ECOLE PRIVEE FLEURIA SCHOOL',
    'codeSecteur': 1,
    'zap': 'TALATA AMPANO',
  },
  {
    'codeEtab': 326111002,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE ANDRARAMBINY',
    'codeSecteur': 1,
    'zap': 'VINANITELO',
  },
  {
    'codeEtab': 326111004,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE IHOROVA',
    'codeSecteur': 1,
    'zap': 'VINANITELO',
  },
  {
    'codeEtab': 326111005,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE SAHAMA',
    'codeSecteur': 1,
    'zap': 'VINANITELO',
  },
  {
    'codeEtab': 326111006,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE TANAMBAO',
    'codeSecteur': 1,
    'zap': 'VINANITELO',
  },
  {
    'codeEtab': 326111007,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE ITANJO',
    'codeSecteur': 1,
    'zap': 'VINANITELO',
  },
  {
    'codeEtab': 326111008,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE AMBALAVAO ANTANIMENA',
    'codeSecteur': 1,
    'zap': 'VINANITELO',
  },
  {
    'codeEtab': 326121002,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE TANAMBAO',
    'codeSecteur': 1,
    'zap': 'VOHIBATO OUEST',
  },
  {
    'codeEtab': 326121003,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE AMBODITANJONA',
    'codeSecteur': 1,
    'zap': 'VOHIBATO OUEST',
  },
  {
    'codeEtab': 326131003,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE FOMADION\'I MARIA LAMOSINA',
    'codeSecteur': 1,
    'zap': 'LAMOSINA',
  },
  {
    'codeEtab': 326131004,
    'nomEtab': 'ECOLE PRIVEE ANTSAHABE TANIDITRA',
    'codeSecteur': 1,
    'zap': 'LAMOSINA',
  },
  {
    'codeEtab': 326131005,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE AMBALATELO',
    'codeSecteur': 1,
    'zap': 'VOHIMARINA',
  },
  {
    'codeEtab': 326131006,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE AMBALAVAO LAZAINARIVO',
    'codeSecteur': 1,
    'zap': 'VOHIMARINA',
  },
  {
    'codeEtab': 326131007,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE AMBATANDRANO',
    'codeSecteur': 1,
    'zap': 'LAMOSINA',
  },
  {
    'codeEtab': 326131008,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE AMBATOHARANANA',
    'codeSecteur': 1,
    'zap': 'LAMOSINA',
  },
  {
    'codeEtab': 326131011,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE IJOBO',
    'codeSecteur': 1,
    'zap': 'LAMOSINA',
  },
  {
    'codeEtab': 326131012,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE IAVONIMANANA',
    'codeSecteur': 1,
    'zap': 'LAMOSINA',
  },
  {
    'codeEtab': 326131013,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE MAHASILA',
    'codeSecteur': 1,
    'zap': 'VOHIMARINA',
  },
  {
    'codeEtab': 326131015,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE TAMBOHOANIVO',
    'codeSecteur': 1,
    'zap': 'VOHIMARINA',
  },
  {
    'codeEtab': 326131016,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE TEAROMIZAHA',
    'codeSecteur': 1,
    'zap': 'VOHIMARINA',
  },
  {
    'codeEtab': 326131017,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE VOATAVOLEMAKA',
    'codeSecteur': 1,
    'zap': 'LAMOSINA',
  },
  {
    'codeEtab': 326131027,
    'nomEtab': 'LYCEE SAINT FRANCOIS XAVIER AMBATOLAHY',
    'codeSecteur': 1,
    'zap': 'VOHIMARINA',
  },
  {
    'codeEtab': 326131029,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE LAVAHATSARA',
    'codeSecteur': 1,
    'zap': 'LAMOSINA',
  },
  {
    'codeEtab': 326131030,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE TAMBOHOBE',
    'codeSecteur': 1,
    'zap': 'VOHIMARINA',
  },
  {
    'codeEtab': 326141001,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE AMBOASARIMARO',
    'codeSecteur': 1,
    'zap': 'VOHITRAFENO',
  },
  {
    'codeEtab': 326141002,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE AMPANDRAMBATO I',
    'codeSecteur': 1,
    'zap': 'VOHITRAFENO',
  },
  {
    'codeEtab': 326141004,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE SAMBOHOVA',
    'codeSecteur': 1,
    'zap': 'VOHITRAFENO',
  },
  {
    'codeEtab': 326141005,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE VOHITRAFENO',
    'codeSecteur': 1,
    'zap': 'VOHITRAFENO',
  },
  {
    'codeEtab': 326141007,
    'nomEtab': 'ECOLE PRIVEE RAINISOALAMBO VATOFOTSY',
    'codeSecteur': 1,
    'zap': 'VOHITRAFENO',
  },
  {
    'codeEtab': 326151001,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE JEAN BOSCO TAMBOHOMANDREVO',
    'codeSecteur': 1,
    'zap': 'ANJANOMANANA TSIMIAVAKA',
  },
  {
    'codeEtab': 326151002,
    'nomEtab': 'ECOLE PRIVEE CATHOLIQUE TAMBOHOBE II',
    'codeSecteur': 1,
    'zap': 'ANJANOMANANA TSIMIAVAKA',
  },
  {
    'codeEtab': 326161001,
    'nomEtab': 'COLLEGE MARIA MANJAKA AMBOAVONA',
    'codeSecteur': 1,
    'zap': 'LAMOSINA',
  },
];
